### ISSUE TITLE
component=helm error="error creating helm client: services \"tiller-deploy\" not found"

### ISSUE THREAD

**Issue by lcsfreire** [helm/helm-2to3#101]
Hello, 
after move releases from v2 to v3, the helm operator isn't able to apply the changes done at helmreleases and is logs the error: 
caller=helm.go:78 component=helm error="error creating helm client: services \"tiller-deploy\" not found"
It's possible to fix this?
Best Regards

**Comment by rimusz** [comment]
the helm operator you are using needs to support helm v3

**Comment by lcsfreire** [comment]
any guidance how to do it?
Thanks

**Comment by rimusz** [comment]
it is not part of this project, so you need to contact helm operator maintainers
