### ISSUE TITLE
How does this work with CircleCI?

### ISSUE THREAD

**Issue by Bajix** [helm/helm-2to3#105]
I'm very new to Helm, and I've inherited a Helm 2 project using CI via CircleCI and AWS EKS. As the repos etc are all on CircleCI, how should this upgrade process work? Does the upgrade from 2 to 3 affect any files that are in source control, or is this solely to not break deployment artifacts? Do I even need to do this upgrade at all or can I simply arbitrarily use Helm 3 and then rely on the CI to run from an older commit/image/cache, or in doing such would that be a foot gun moment? Does the upgrade process need to be pushed through Circle CI via committing some procedure?

**Comment by hickeyma** [comment]
@Bajix [helm-2to3](https://github.com/helm/helm-2to3/) is a tool to help with migrating Helm 2 managed cluster to Helm 3.  The [migration doc](https://helm.sh/docs/topics/v2_v3_migration/) provides good context and description of the migration process for Helm.

If you are new to Helm then I would suggest reading the documentation first to get an understanding of Helm:

- v2 docs: https://v2.helm.sh/docs/

- v3 docs: https://helm.sh/docs/

- v3 Release doc: https://helm.sh/blog/helm-3-released/

Let me know if you need anymore information. I would also suggest bouncing questions in the Helm slack channels: https://github.com/helm/helm#community-discussion-contribution-and-support

**Comment by hickeyma** [comment]
Closing as question is answered.
