### ISSUE TITLE
--kube-context parameter not respected

### ISSUE THREAD

**Issue by edvald** [helm/helm-2to3#106]
Just ran into this bug. Turns out you need to set your default context to the one you're interested in, because the plugin ignores the `--kube-context` parameter (which is a global param on the `helm` CLI). 

This is actually kinda dangerous (more so than #11) because you could easily accidentally interact with the wrong cluster and screw things up, thinking your normal global Helm parameters work as expected. Thankfully, I was just messing with a dev environment when I bumped into this.

**Comment by hickeyma** [comment]
@edvald The plugin does not support the `--kube-context` flag. This flag is specific to Helm only. 

It should work similar to `kubectl` access using [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).

**Comment by edvald** [comment]
That's understood. I guess it's partly an artefact of the `helm` plugin system design, but I think it's kinda dangerous to silently accept the `--kube-context` parameter and then ignore it. I'd suggest either giving an error/warning when it's specified or implementing support for it, to avoid potential accidents or confusion when migrating.

**Comment by hickeyma** [comment]
@edvald Are you sure that the flag was accepted silently? I just ran it and got this:

```console
$ helm 2to3 convert chrt-106 --dry-run --kube-context
Error: unknown flag: --kube-context
```

**Comment by edvald** [comment]
It turns out the ordering matters. If you put `--kube-context` before `2to3` it's silently dropped, otherwise the error is thrown.

**Comment by hickeyma** [comment]
Ok that makes sense; that is passing the flag to helm and not the plugin. Not much the plugin can do about that!

**Comment by edvald** [comment]
Well, except to actually use the environment variable that `helm` sets: https://helm.sh/docs/topics/plugins/#environment-variables

That would be the expected behavior imo.

**Comment by hickeyma** [comment]
Trying that as well, cannot get it to work:

```console
$ helm --kube-context 2to3 convert chrt-106 --dry-run
helm.go:71: context "2to3" does not exist
```

What is the command you run?

**Comment by edvald** [comment]
You just missed the value for the `--kube-context` parameter, e.g. `--kube-context=foo`

**Comment by hickeyma** [comment]
@edvald Seems some weird behaviour depending on how running.

I think regardless it would be good to have this functionality. Setting as a feature that I will work on.

**Comment by hickeyma** [comment]
@edvald #116 now merged, adding the functionality
