### ISSUE TITLE
Requesting resources outside of set kube-context namespace

### ISSUE THREAD

**Issue by danielc103** [helm/helm-2to3#107]
Dry run using service account on in a specified namespace fails due to secrets request outside of set namespace 
```cli
kubectl config set-cluster kube --server="$CLUSTER_SERVER" --insecure-skip-tls-verify=true
kubectl config set-credentials "helm-deployer" --token="$HELM_TOKEN"
kubectl config set-context $CLUSTER_NAMESPACE-deploy  --cluster=kube --namespace=$CLUSTER_NAMESPACE --user=helm-deployer
kubectl config use-context $CLUSTER_NAMESPACE-deploy
helm 2to3 convert helm3t-nginx --dry-run --tiller-out-cluster
```
```
Release "helm3t-nginx" will be created.
Error: secrets is forbidden: User "system:serviceaccount:test:helm-deployer" cannot list secrets in the namespace "kube-system": no RBAC policy matched
Error: plugin "2to3" exited with error
```
Expected behavior - only request resources in namespace set in kube-context.

**Comment by hickeyma** [comment]
@danielc103  Would you be like to add to the README (https://github.com/helm/helm-2to3#prerequisite) about needing access to the Tiller namespace to retrieve the v2 releases?

**Comment by hickeyma** [comment]
@danielc103 Just wondering if your cluster is RBAC enabled? If so, is Tiller deployed and running in the cluster? Can check with command if deployed to `kube-system`: `kubectl get pods -n kube-system -l app=helm`

Can you do a `helm ls` (using Helm v2) on CLI where you run the `convert` command? i would like to see the output. Trying to work out if this is an issue with RBAC and service account.

**Comment by danielc103** [comment]
Yes, I can definitely add to the readme!

Yes our cluster is RBAC enabled. We are restricting developer use by creating a 'helm-deployer' service accounts in their owned namepsace only for the deployments.
 
`User "system:serviceaccount:test:helm-deployer"`

This restricts any kubectl commands outside the namespace and will throw the forbidden errors.  We are also using  tillerless deployment, so no dice even if I could. 

```cli
$ helm ls
NAME                      	REVISION	UPDATED                 	STATUS  	CHART                 	APP VERSION	NAMESPACE
consul                    	29      	Fri Dec  6 19:33:36 2019	DEPLOYED	consul-1.0.0          	           	test
helm3t                    	1       	Wed Jan  8 18:40:01 2020	DEPLOYED	nginx-5.1.1           	1.16.1     	test
migration                 	22      	Wed Jul  3 17:40:29 2019	DEPLOYED	migration-test-0.1.0  	1.0        	test
```

**Comment by hickeyma** [comment]
Ok, that explains it. I think adding to the README would be great. I will assign the issue to you and push a PR when you get a chance. Thanks.
