### ISSUE TITLE
plugin install error on Windows - "Error: The Remote does not match the VCS endpoint"

### ISSUE THREAD

**Issue by jonstelly** [helm/helm-2to3#108]
Windows 10, try to install plugin and I got:

helm version:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

install command:

``helm plugin install https://github.com/helm/helm-2to3 --debug`

Error:
```
Error: The Remote does not match the VCS endpoint
helm.go:76: [debug] The Remote does not match the VCS endpoint
```

Turns out I had a temp directory `C:\Users\ME\AppData\Local\Temp\helm` that must have had bad data in it.  I deleted that helm directory and that fixed the issue.

Closing this issue so it exists more as documentation for searches.

**Comment by hickeyma** [comment]
Thanks for the information @jonstelly
