### ISSUE TITLE
Not recognized multiple kube-config files in KUBECONFIG env variable

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm-2to3#11]
Hello,

I have a bunch of clusters and merging kubeconfig files. 
Looks like it is not working with this approach.
I have tested only with one kubeconfig file and it is working fine.

```
helm 2to3 convert dummy-dev --dry-run
NOTE: This is in dry-run mode, the following actions will not be executed.
Run without --dry-run to take the actions described below:

Release "dummy-dev" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "dummy-dev" will be created.
2019/09/04 17:54:20 stat /Users/osema/.bluemix/plugins/container-service/clusters/Helm-2-3/kube-config-Helm-2-3.yml:/Users/osema/.bluemix/plugins/container-service/clusters/wx-dev-001/kube-config-wx-dev-001.yml:/Users/osema/.bluemix/plugins/container-service/clusters/playground-AutomationQA/kube-config-playground-AutomationQA.yml:/Users/osema/.bluemix/plugins/container-service/clusters/play_openshift/kube-config-play_openshift.yml:/Users/osema/.bluemix/plugins/container-service/clusters/wx-dev-003/kube-config-wx-dev-003.yml: no such file or directory
Error: plugin "2to3" exited with error
```

**Comment by hickeyma** [comment]
@alexandrsemak It probably needs to handle different kubeconfigs instead of using the standard/default. However, the error message is rather confusing. Just trying to get better understanding of your set-up so I can troubleshoot this.

For the case that is working, how are you using one kubeconfig file wrt:
- Helm 2
- Helm 3
- plugin

For the case that is not working, how are you using multiple kubeconfig files wrt:
- Helm 2
- Helm 3
- plugin

**Comment by alexandrsemak** [comment]
@hickeyma 
With multiple kubeconfig i have KUBECONFIG=$cluster1:/$cluster2:.... and kubectx for switching between them.
With single kubeconfig file I have used the same evn but just left only one kubeconfig KUBECONFIG=$cluster1

**Comment by hickeyma** [comment]
@alexandrsemak Does Helm v2 and Hem v3 have any issues with the multiple kubeconfigs? Do you have to pass `--kubeconfig ` for running Helm commands?

**Comment by alexandrsemak** [comment]
@hickeyma 
with kubectx i don't use `--kubeconfig` 
kubectx use `kubectl config set-context` under the hood

**Comment by rimusz** [comment]
I was able to reproduce it with `export KUBECONFIG=$cluster1:/$cluster2` got the same
error:
```
$ helm3 2to3 convert --tiller-out-cluster --dry-run mysql
NOTE: This is in dry-run mode, the following actions will not be executed.
Run without --dry-run to take the actions described below:

Release "mysql" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "mysql" will be created.
2019/09/25 10:26:55 stat /Users/rimasm/.kube/test-cluster-1_config:/Users/rimas/.kube/test-cluster-2_config: no such file or directory
Error: plugin "2to3" exited with error
```

**Comment by rimusz** [comment]
ideally it should not be part of the plugin, we could just add a note, single kubeconfig is only supported, as otherwise plugin will get too messy

**Comment by alexandrsemak** [comment]
why plugin just not able use current `context`? which use `kubectl` with `set-context`

**Comment by rimusz** [comment]
it needs to be implemented :)

**Comment by rimusz** [comment]
How to use single `kubeconfig` in env var `KUBECONFIG` was documented in #63

**Comment by hickeyma** [comment]
Finally, getting back to this issue again.

I have tracked it down to an issue with the [helm-plugin-utils library](https://github.com/maorfr/helm-plugin-utils). [Issue](https://github.com/maorfr/helm-plugin-utils/issues/1) was already raised in project and have pushed a [PR](https://github.com/maorfr/helm-plugin-utils/pull/3) to fix it
