### ISSUE TITLE
[question] Downtime migrating from helm 2 to helm 3 ?

### ISSUE THREAD

**Issue by emirot** [helm/helm-2to3#113]
Hi there,

I would like to use from helm2 to helm3, I'm wondering if it will create any downtime when migrating the chart over helm3.
Is it intended to be transparent for external users ?
If the question is relevant it would be great to add it the doc or faq.

**Comment by rimusz** [comment]
there is no downtime as only chart’s release data gets migrated

**Comment by hickeyma** [comment]
@emirot The plugin is a tool to perform in-situ migration for Helm v2 to v3. Migration is described in the [Helm migration doc](https://helm.sh/docs/topics/v2_v3_migration/).

Let me know if this answers your question.

**Comment by hickeyma** [comment]
@emirot Did it help answer your question in https://github.com/helm/helm-2to3/issues/113#issuecomment-579175612?

**Comment by emirot** [comment]
@hickeyma Yes thank you !!
I'm using it.

**Comment by hickeyma** [comment]
Ok, closing as question answered.
