### ISSUE TITLE
after migrating charts, attempting to upgrade gets: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by bitsofinfo** [helm/helm-2to3#123]
I have a helm2 chart that has a live release running fine. 

The chart does not define `clusterIP` anywhere.

I convert the chart to helm3 w/ this plugin

I then do an upgrade on that chart via helm3 and and run into this error `spec.clusterIP: Invalid value: "": field is immutable`

referenced here: https://github.com/helm/helm/issues/6378

**Comment by bitsofinfo** [comment]
Just a note, I don't think this is related to this plugin, its just some odd behavior difference between helm2 and helm3 in regards to the implementation of force I guess? https://github.com/helm/helm/issues/7082

**Comment by bacongobbler** [comment]
Yeah, this is unrelated to the plugin. There's nothing actionable here on the plugin's end. Let's continue the conversation in helm/helm#7082. Thanks!
