### ISSUE TITLE
Error migration : spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by sylvainmouquet** [helm/helm-2to3#125]
Hello,

I have this error : https://github.com/helm/helm/issues/6378
In the release of helm2 there is the clusterIp is hard code and when we try to deploy with helm3 we have the error.

**Comment by hickeyma** [comment]
Duplicate of #123

**Comment by hickeyma** [comment]
Closing as it is a duplicate issue.
