### ISSUE TITLE
helm plugin install plugin.yaml metadata missing error

### ISSUE THREAD

**Issue by RudyBone** [helm/helm-2to3#130]
I downloaded the helm-2to3_0.3.1_linux_amd64.tar.gz and unzipped.  When went to install the plugin using helm 3:

helm plugin install

Error: plugin metadata (plugin.yaml) missing

**Comment by hickeyma** [comment]
@RudyBone I found an issue with the latest release as follows:

```console
$ tar -xvzf helm-2to3_0.4.0_linux_amd64.tar.gz 
LICENSE
completion.yaml
plugin.yaml
2to3

$ helm plugin install .
sh: 1: scripts/install_plugin.sh: not found
```

**Comment by rimusz** [comment]
@hickeyma we never had `scripts/install_plugin.sh` in the release bundles

**Comment by rimusz** [comment]
let me do a PR to fix it

**Comment by rimusz** [comment]
fix in the #131

**Comment by RudyBone** [comment]
So can I re-download the helm-2to3_0.3.1_linux_amd64.tar.gz file now and it will have the fix in it?

**Comment by rimusz** [comment]
it wasn't released yet

**Comment by rimusz** [comment]
@RudyBone please download the latest plugin version 0.4.1, which has the fix.
