### ISSUE TITLE
Unable to install helm-2to3 plugin v0.5.0

### ISSUE THREAD

**Issue by MaksymDolgykh** [helm/helm-2to3#133]
Looks like a new [version](https://github.com/helm/helm-2to3/commit/3f8f18ecd05f2875be89eb0fab673e1eb1f4abbb) was released recently and looks like the build is broken.
When I try install it I get following error
```
helm plugin install https://github.com/helm/helm-2to3.git
Downloading and installing helm-2to3 v0.5.0 ...
https://github.com/helm/helm-2to3/releases/download/v0.5.0/helm-2to3_0.5.0_linux_amd64.tar.gz
tar: invalid magic
tar: short read
Error: plugin install hook for "2to3" exited with error
```

**Comment by rimusz** [comment]
sorry for the delay it got released https://github.com/helm/helm-2to3/releases/tag/v0.5.0

**Comment by hickeyma** [comment]
Thanks for building the release @rimusz 👏
