### ISSUE TITLE
plugin fails to install: wrong version in plugin.yaml

### ISSUE THREAD

**Issue by tgunsch** [helm/helm-2to3#134]
installing the plugin fails:

```
helm3 plugin install https://github.com/helm/helm-2to3
Downloading and installing helm-2to3 v0.5.0 ...
https://github.com/helm/helm-2to3/releases/download/v0.5.0/helm-2to3_0.5.0_linux_amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: plugin install hook for "2to3" exited with error
```

The problem seems to be the version number 0.5.0 in `~/.local/share/helm/plugins/helm-2to3/plugin.yaml` which is not yet released. Unfortunately this occurs during build of the build-agent-image, so I can't manually edit `~/.local/share/helm/plugins/helm-2to3/plugin.yaml`

**Comment by hickeyma** [comment]
@tgunsch Sorry about that but the 0.5.0had not been built yet. It is now built, thanks to @rimusz.

Can you try it again and see if it works?

**Comment by tgunsch** [comment]
> @tgunsch Sorry about that but the [0.5.0](https://github.com/helm/helm-2to3/releases/tag/v0.5.0) had not been built yet.  It is now built, thanks to @rimusz. 
> 
> Can you try it again and see if it works?

Yes it works :+1: 

Thx very much, I close the issue.
