### ISSUE TITLE
RELEASE_NAME has no deployed releases

### ISSUE THREAD

**Issue by itninja-hue** [helm/helm-2to3#136]
what I am doing:
```bash
helm3 2to3 convert microservice-notification --tiller-ns "dev-microservice-notification" --label "app=helm"

2020/03/17 11:48:30 Release "microservice-notification" will be converted from Helm v2 to Helm v3.
2020/03/17 11:48:30 [Helm 3] Release "microservice-notification" will be created.
Error: microservice-notification has no deployed releases
```
Tiller deployment Labels: 
```yaml
Labels:                 
  app=helm
  name=tiller
```
Helm Versions:
```bash
helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

helm3 version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"} 
```
Expected behavior: 
successfully migrate.

Questions:
1- What am i messing ? 
2- How can i increase verbosity so i can debug, "other than --debug which just reprints  the error msg with just a debug keyword upfront "

**Comment by itninja-hue** [comment]
So the way my helm was set it saves all release secrets in a different namespace than the actual release, to be specific it saves release secrets in kube-system and releases on dev-microservice-notification; 
I got mislead  by the following:
``` text
--label string   label to select Tiller resources by (default "OWNER=TILLER")
```
As mentioned in the issue description i thought that it is mainly looking for tiller POD, and it will figure out itself where secrets are stored, just like helm saves the secrets in different namespace and allows me to do rollbacks and upgrade like it is expected.

The workaround:
Since no flag was provided to specify what namespace to look for secrets in, i Had to move them to the same namespace (from kube-system to dev-microservice-notification) (NOT RECOMMENDED)

A one liner to copy multiple secrets from a namespace to another (kube-system to dev-microservice-notification) 

```bash
kubectl get secrets -n kube-system -l OWNER=TILLER,NAME=microservice-notification --export -o yaml | sed 's/kube\-system/dev-microservice-notification/g' | kubectl apply -f -
```
Migration:
```
helm3 2to3 convert microservice-notification --tiller-ns "dev-microservice-notification"  --tiller-out-cluster --dry-run
2020/03/17 15:23:02 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/03/17 15:23:02 Run without --dry-run to take the actions described below:
2020/03/17 15:23:02 
2020/03/17 15:23:02 Release "microservice-notification" will be converted from Helm v2 to Helm v3.
2020/03/17 15:23:02 [Helm 3] Release "microservice-notification" will be created.
...
2020/03/17 15:23:03 [Helm 3] ReleaseVersion "microservice-notification.v41" will be created.
```

**Comment by hickeyma** [comment]
@itninja-hue I think your issue was that you set `--tiller-ns "dev-microservice-notification"`.  The flag `--tiller-ns` is to specify the namespace of the Tiller instance and not to be the namespace of the release.  In Helm v2, all release data is stored in the namespace of Tiller instance. By default, that namespace is `kube-system`. When converting, the plugin will get the namespace of the release from the release metadata and therefore save it in that namepsace.

**Comment by itninja-hue** [comment]
@hickeyma In my case i deploy tiller pods per namespace (restricted to deploying resources only in that namespace), and it saves all releases configurations in another namespace ("kube-system"), so  i used --tiller-ns as mentioned in docs to specify the namespace of the tiller pod, but what happened is, that 2to3 plugin supposed that i keep release secrets in the same namespace, thats why it triggered no deployed release error, which makes sense since no secrets where OWNER=TILLER is found. My use case is very specific, but thank you for the plugin its very useful and saved me a lot of scripting and manual work.

**Comment by hickeyma** [comment]
@itninja-hue Thanks for the explanation of your set-up. It sounds like a customised Helm set-up! :)
