### ISSUE TITLE
Move repository to Helm org

### ISSUE THREAD

**Issue by rimusz** [helm/helm-2to3#14]
I think the current stage of the plugin is good, we should move it to helm org, then cut a first release

**Comment by hickeyma** [comment]
l raise this today at the Helm dev weekly meeting.

**Comment by hickeyma** [comment]
There was a good response to moving the plugin to the Helm org. It was recommended to send a mail to the Helm org list proposing the move. Mail is sent, awaiting feedback.

**Comment by rimusz** [comment]
done
