### ISSUE TITLE
Add support for helm plugin update

### ISSUE THREAD

**Issue by hickeyma** [helm/helm-2to3#141]
Currently when you want to update the plugin version, you need to remove and then install. It would be nice to be able to just do a `helm plugin update`.

Thanks for finding @morstad

**Comment by hickeyma** [comment]
This requires adding the `update` hook to the plugin and adding a new script to adding the changes to the installm script where needed.

**Comment by rimusz** [comment]
hmm, I can upgrade the plugin with the current version and install script:
```
$ helm3 plugin ls
NAME   	VERSION	DESCRIPTION
2to3   	0.5.0  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

```
$ helm3 plugin update 2to3
Downloading and installing helm-2to3 v0.5.1 ...
https://github.com/helm/helm-2to3/releases/download/v0.5.1/helm-2to3_0.5.1_darwin_amd64.tar.gzUpdated plugin: 2to3
```

```
$ helm3 plugin ls
NAME   	VERSION	DESCRIPTION
2to3   	0.5.1  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

**Comment by hickeyma** [comment]
Sorry, my bad. I had an issue in my environment.

**Comment by hickeyma** [comment]
Closing as working as expected.
