### ISSUE TITLE
error when reading response body

### ISSUE THREAD

**Issue by BoOgatti** [helm/helm-2to3#142]
Hi, I am trying to convert my releases from v2 to v3 and one of them I get an error:
```
helm3 2to3 convert foo-bar --tiller-ns some-project --namespace some-project --release-storage configmaps

2020/03/30 12:26:40 Release "foo-bar" will be converted from Helm v2 to Helm v3.
2020/03/30 12:26:40 [Helm 3] Release "foo-bar" will be created.
Error: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 3; INTERNAL_ERROR
Error: plugin "2to3" exited with error
```

I suspect one of the problem it's size of my deployment (it has a really big configmap) which entails a connection timeout. How can I to diagnose this issue, because I can't see any flags like `debug` or `timeout`? Can I convert it manually?

_Helm v3.1.2
Plugin v0.5.0_

**Comment by hickeyma** [comment]
@BoOgatti Thanks for raising this. A few things to better understand the problem:

- Can you show the output of the following command: `kubectl get configmap -n <tiller_namespace> -l "OWNER=TILLER" | grep "foo-bar"`?
- Do you have timeout issues when you run this command: `helm2 get foo-bar` ?

FYI, if Tiller is running in the cluster, then the `convert` command would be as follows: `helm3 2to3 convert foo-bar --tiller-ns <tiller_namespace>`. No need for the other flags.

**Comment by BoOgatti** [comment]
Yeah, sure
```
$ kubectl get configmap -n some-project -l "OWNER=TILLER" | grep "foo-bar"
foo-bar.v1         1      476d
foo-bar.v10        1      474d
foo-bar.v100       1      336d
foo-bar.v101       1      335d
...
...
...
foo-bar.v99       1      335d
```
```
$ helm2 get foo-bar --tiller-namespace some-project
REVISION: 421
RELEASED: Mon Mar 30 12:07:05 2020
CHART: foo-bar-0.0.2
USER-SUPPLIED VALUES:
...
...
...

$ helm2 get foo-bar --tiller-namespace some-project | wc -l
6138
(really huge config)
```
helm2 operations can consume up to 20 seconds (it looks like hanging for some time) but always completed

**Comment by hickeyma** [comment]
It would seem a lot of data is being returned (possibly 101 ConfigMaps i.e. release versions) and this could be stressing the API call to the cluster. The plugin retrieves the release data using the k8s API directly and not via Helm v2.

How many release versions do you have for `foo-bar`. Do you need all of them or could you cull some/most of them?

**Comment by BoOgatti** [comment]
Yay! Made some cleanup and it works, looks like overloaded API. Thx @hickeyma

**Comment by IdanAdar** [comment]
What cleanup did you do? I am hitting this as well.

**Comment by BoOgatti** [comment]
@IdanAdar something like this:
```
for i in {1..325}; do kubectl delete configmaps goods.v${i}; done
```

**Comment by hickeyma** [comment]
@IdanAdar Following on from @BoOgatti  above..

This command returns all release versions/revisions:
`kubectl get configmap\secret -l OWNER=TILLER,NAME=<release_name> --namespace 
<tiller_namespace>`

For example: 
```console
$ kubectl get configmap -l OWNER=TILLER,NAME=mychart --namespace kube-system`
NAME             DATA   AGE
oldapi-chrt.v1   1      8d
oldapi-chrt.v2   1      8d
```

You can then delete using `kubectl delete configmap\secret <release_version_name> --namespace <tiller_namespace>`

Note:
- Release revision/version start at `1` and go up in increments of 1
- Some revisions may already be removed, so `1` might not be the first and it is possible that there are gaps of more than 1
- ConfigMaps by default but secrets can be configured also
- On a Tiller instance basis

The number of ConfigMaps have hit folks in the past using Helm 2 as there is a ConfigMap created per release version/revision. It is therefore recommended to use the `--history-max` flag with `helm init`. Some details in [docs](https://v2.helm.sh/docs/using_helm/#initialize-helm-and-install-tiller). Helm 3 changed this as follows for `helm upgrade` command:
`--history-max int              limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)`.
