### ISSUE TITLE
Issue with using helm2-3 plugin

### ISSUE THREAD

**Issue by vsaibinaysoma** [helm/helm-2to3#143]
Hi Currently i have used the helm 2 to 3 plugin to move and migrate from helm v2 to helm v3. But after the migration i am not running helm v2 and v3 in conjunction. I moved helm v3 into /usr/local/bin/>> path and then the deleted the old helm folder. I am able to run commands as expected with helm. All the files and workloads seems to be working fine, the workloads that were running version 2. However when i trigger my jenkins deployment  the helm fetch command which is "helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory " which is pulling the chart from helm virtual repository and it fails with an error repo not found.

When i do the **helm repo list** as below the repo is clearly there
[root@devminion01 local]# helm repo list
NAME                      	URL                                                        
stable                    	https://kubernetes-charts.storage.googleapis.com           
jfrog                     	https://charts.jfrog.io                                    
artifactory.it.jetblue.com	https://artifactory.it.jetblue.com/artifactory/helm-virtual

the **reposotiries.yaml** is managed with salt stack and here is how it looks like:

apiVersion: v1
generated: 2018-07-20T03:36:44.646112339Z
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://kubernetes-charts.storage.googleapis.com
  username: ""
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: artifactory.it.jetblue.com
  password: PS4b2u5-nkWE=D
  url: https://artifactory.it.jetblue.com/artifactory/helm-virtual
  username: helm

**helm env output:**

[root@devminion01 repository]# helm env
HELM_BIN="helm"
HELM_DEBUG="false"
HELM_KUBECONTEXT=""
HELM_NAMESPACE="default"
HELM_PLUGINS="/root/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/root/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/root/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/root/.config/helm/repositories.yaml"

Is this an issue with moving from v2 to V3 and is a limitation with helm 3 or am i missing anything here.?

Your inputs at the earliest will help me. Thank you.

**Comment by rimusz** [comment]
Ok I did some testing with helm v3 cli:
```
$ helm repo add artifactory.it.jetblue.com  https://artifactory.it.jetblue.com/artifactory/helm-virtual --username helm --password PS4b2u5-nkWE=D
"artifactory.it.jetblue.com" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "artifactory.it.jetblue.com" chart repository
Update Complete. ⎈ Happy Helming!⎈

$ helm3 pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory

$ ls -alhartifactory/
total 32
drwxr-xr-x   7 user  staff   224B Apr  1 17:24 .
drwxr-xr-x   4 user  staff   128B Apr  1 17:24 ..
-rw-r--r--   1 user  staff   780B Apr  1 17:24 CHANGELOG.txt
-rw-r--r--   1 user staff   105B Apr  1 17:24 Chart.yaml
-rw-r--r--   1 user  staff    85B Apr  1 17:24 Jenkinsfile
drwxr-xr-x  14 user  staff   448B Apr  1 17:24 templates
-rw-r--r--   1 user  staff   745B Apr  1 17:24 values.yaml
```

So you are missing `helm repo update` command

**Comment by vsaibinaysoma** [comment]
We are running helm repo update in with the pipeline. Repo update happens as a pre requisite before helm fetch.

[root@dop-salt01 helmchartdeploy]# salt -t 680 "devminion*" state.sls helmchartdeploy  pillar="{'jbname':"artifactory",'version':"6.12.2-rc-0", 'buildenv':"release", 'deployenv': "dev" }"
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/saltapi.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/saltapi.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dop-salt01.c.devops-179400.internal
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'dop-salt01.c.devops-179400.internal_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/bf/ce5c8f28ca0571c800c2adf87ca0c0300da1bb415f30de8eec909f4d1fdafd/.minions.p
[DEBUG   ] get_iter_returns for jid 20200401135622910504 sent to set(['devminion01']) will timeout at 14:07:42.922885
[DEBUG   ] jid 20200401135622910504 return from devminion01
[DEBUG   ] return event: {u'devminion01': {u'jid': u'20200401135622910504', u'retcode': 2, u'ret': {u'module_|-refresh_pillar_|-saltutil.refresh_pillar_|-run': {u'comment': u'Module function saltutil.refresh_pillar executed', u'name': u'saltutil.refresh_pillar', u'start_time': u'13:57:31.978606', u'result': True, u'duration': 8.892, u'__run_num__': 0, u'__sls__': u'helmchartdeploy', u'changes': {u'ret': True}, u'__id__': u'refresh_pillar'}, u'cmd_|-repo_update_|-helm repo update_|-run': {u'comment': u'Command "helm repo update" run', u'name': u'helm repo update', u'start_time': u'13:57:32.072630', u'result': True, u'duration': 2397.223, u'__run_num__': 3, u'__sls__': u'helmchartdeploy', u'changes': {u'pid': 4720, u'retcode': 0, u'stderr': u'', u'stdout': u'Hang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the "jfrog" chart repository\n...Successfully got an update from the "artifactory.it.jetblue.com" chart repository\n...Successfully got an update from the "stable" chart repository\nUpdate Complete. \u2388 Happy Helming!\u2388'}, u'__id__': u'repo_update'}, u'file_|-repositories.yaml_|-/root/.config/repository/repositories.yaml_|-managed': {u'comment': u'File /root/.config/repository/repositories.yaml is in the correct state', u'pchanges': {}, u'name': u'/root/.config/repository/repositories.yaml', u'start_time': u'13:57:32.002995', u'result': True, u'duration': 67.811, u'__run_num__': 2, u'__sls__': u'helmchartdeploy', u'changes': {}, u'__id__': u'repositories.yaml'}, u'cmd_|-chart_deploy_|-helm upgrade devops-artifactory --install artifactory.it.jetblue.com/artifactory --force --kubeconfig /root/.kube/config -f salt-values.yaml --namespace devops_|-run': {u'comment': u'Command "helm upgrade devops-artifactory --install artifactory.it.jetblue.com/artifactory --force --kubeconfig /root/.kube/config -f salt-values.yaml --namespace devops" run', u'name': u'helm upgrade devops-artifactory --install artifactory.it.jetblue.com/artifactory --force --kubeconfig /root/.kube/config -f salt-values.yaml --namespace devops', u'start_time': u'13:58:54.363594', u'result': False, u'duration': 2037.488, u'__run_num__': 6, u'__sls__': u'helmchartdeploy', u'changes': {u'pid': 4847, u'retcode': 1, u'stderr': u'Error: no objects visited', u'stdout': u'Release "devops-artifactory" does not exist. Installing it now.'}, u'__id__': u'chart_deploy'}, u'cmd_|-chart_fetch_|-helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory_|-run': {u'comment': u'Command "helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory" run', u'name': u'helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory', u'start_time': u'13:57:34.470541', u'result': False, u'duration': 71.239, u'__run_num__': 4, u'__sls__': u'helmchartdeploy', u'changes': {u'pid': 4727, u'retcode': 1, u'stderr': u'Error: repo artifactory.it.jetblue.com not found', u'stdout': u''}, u'__id__': u'chart_fetch'}, u'file_|-manage_values_|-/opt/deploy/release/artifactory/salt-values.yaml_|-managed': {u'comment': u'File /opt/deploy/release/artifactory/salt-values.yaml is in the correct state', u'pchanges': {}, u'name': u'/opt/deploy/release/artifactory/salt-values.yaml', u'start_time': u'13:57:34.542055', u'result': True, u'duration': 79821.322, u'__run_num__': 5, u'__sls__': u'helmchartdeploy', u'changes': {}, u'__id__': u'manage_values'}, u'file_|-workdir_exists_|-/opt/deploy/release/artifactory_|-directory': {u'comment': u'Directory /opt/deploy/release/artifactory is in the correct state\nDirectory /opt/deploy/release/artifactory updated', u'pchanges': {}, u'name': u'/opt/deploy/release/artifactory', u'start_time': u'13:57:31.996017', u'result': True, u'duration': 6.848, u'__run_num__': 1, u'__sls__': u'helmchartdeploy', u'changes': {}, u'__id__': u'workdir_exists'}}, u'out': u'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] LazyLoaded nested.output
devminion01:
----------
          ID: refresh_pillar
    Function: module.run
        Name: saltutil.refresh_pillar
      Result: True
     Comment: Module function saltutil.refresh_pillar executed
     Started: 13:57:31.978606
    Duration: 8.892 ms
     Changes:   
              ----------
              ret:
                  True
----------
          ID: workdir_exists
    Function: file.directory
        Name: /opt/deploy/release/artifactory
      Result: True
     Comment: Directory /opt/deploy/release/artifactory is in the correct state
              Directory /opt/deploy/release/artifactory updated
     Started: 13:57:31.996017
    Duration: 6.848 ms
     Changes:   
----------
          ID: repositories.yaml
    Function: file.managed
        Name: /root/.config/repository/repositories.yaml
      Result: True
     Comment: File /root/.config/repository/repositories.yaml is in the correct state
     Started: 13:57:32.002995
    Duration: 67.811 ms
     Changes:   
----------
          ID: repo_update
    Function: cmd.run
        Name: helm repo update
      Result: True
     Comment: Command "helm repo update" run
     Started: 13:57:32.072630
    Duration: 2397.223 ms
     Changes:   
              ----------
              pid:
                  4720
              retcode:
                  0
              stderr:
              stdout:
                  Hang tight while we grab the latest from your chart repositories...
                  ...Successfully got an update from the "jfrog" chart repository
                  ...Successfully got an update from the "artifactory.it.jetblue.com" chart repository
                  ...Successfully got an update from the "stable" chart repository
                  Update Complete. ⎈ Happy Helming!⎈
----------
          ID: chart_fetch
    Function: cmd.run
        Name: helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory
      Result: False
     Comment: Command "helm pull --untar --version 6.12.2-rc-0 artifactory.it.jetblue.com/artifactory" run
     Started: 13:57:34.470541
    Duration: 71.239 ms
     Changes:   
              ----------
              pid:
                  4727
              retcode:
                  1
              stderr:
                  Error: repo artifactory.it.jetblue.com not found
              stdout:
----------
          ID: manage_values
    Function: file.managed
        Name: /opt/deploy/release/artifactory/salt-values.yaml
      Result: True
     Comment: File /opt/deploy/release/artifactory/salt-values.yaml is in the correct state
     Started: 13:57:34.542055
    Duration: 79821.322 ms
     Changes:   
----------
          ID: chart_deploy
    Function: cmd.run
        Name: helm upgrade devops-artifactory --install artifactory.it.jetblue.com/artifactory --force --kubeconfig /root/.kube/config -f salt-values.yaml --namespace devops
      Result: False
     Comment: Command "helm upgrade devops-artifactory --install artifactory.it.jetblue.com/artifactory --force --kubeconfig /root/.kube/config -f salt-values.yaml --namespace devops" run
     Started: 13:58:54.363594
    Duration: 2037.488 ms
     Changes:   
              ----------
              pid:
                  4847
              retcode:
                  1
              stderr:
                  Error: no objects visited
              stdout:
                  Release "devops-artifactory" does not exist. Installing it now.

Summary for devminion01
------------
Succeeded: 5 (changed=4)
Failed:    2
------------
Total states run:     7
Total run time:  84.411 s

**Comment by vsaibinaysoma** [comment]
We are getting repo not found.

**Comment by rimusz** [comment]
not sure what's the issue, but it is not related to the `2to3` plugin

**Comment by vsaibinaysoma** [comment]
I need more insights on this plugin. How can you prove it is not an issue with the plugin. I used this plugin and after i went ahead with migration to helm 3. My local repo was corrupted and i deleted it to avoid failures in my jenkins builds. Does the local repo get created by default with the helm client and configuration. How can i restore the local repo  or helm 3 can function without the local repo.?
