### ISSUE TITLE
execute helm 2to3 cleanup , the resources are still existed

### ISSUE THREAD

**Issue by qianying-99** [helm/helm-2to3#144]
the release can't listed from helm2 command, but the resources are still existed in the k8s cluster.
So the clean up  command did't delete helm releases , just clean up the releases infomation from tiller

**Comment by hickeyma** [comment]
@qianying-99 Need to ask you some questions to try and understand the issue better.

Are you saying that when you run the cleanup, the release information for Helm v2 (e.g. ` kubectl get configmap -n kube-system -l "OWNER=TILLER"`) is gone and `helm2 ls` returns no release information? However, you still see the Kubernetes objects in the cluster for that release?

**Comment by qianying-99** [comment]
Yes, `kubectl get pod -n <namespace>` , everything is also existed

**Comment by qianying-99** [comment]
> @qianying-99 Need to ask you some questions to try and understand the issue better.
> 
> Are you saying that when you run the cleanup, the release information for Helm v2 (e.g. ` kubectl get configmap -n kube-system -l "OWNER=TILLER"`) is gone and `helm2 ls` returns no release information? However, you still see the Kubernetes objects (e.g. pods etc.) in the cluster for that release?

Yes, kubectl get pod -n <namespace> , everything is also existed

**Comment by hickeyma** [comment]
@qianying-99 Then it is working as expected.

When you run the `convert` command its goal is to create release metadata ONLY for Helm v3 for a release which was deployed using Helm v2. It creates this release metadata but does not touch the Kubernetes resources which were deployed by the chart in Helm v2. When you do the `convert` it  is for Helm v3 to manage this release and the deployed resources.

The `cleanup` command is to remove the Helm v2 release metadata ONLY. It does not handle the deployed Kubernetes resources as it is expected that Helm v3 is now managing them.

Hope this helps answer your issue.

**Comment by hickeyma** [comment]
Does this answer your question @qianying-99?

**Comment by qianying-99** [comment]
Yes, but if i don't need these releases , i have to clean up manually.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Hickey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上6:28
收件人:&nbsp;"helm/helm-2to3"<helm-2to3@noreply.github.com&gt;;
抄送:&nbsp;"Aurora"<2654733670@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [helm/helm-2to3] execute helm 2to3 cleanup , the resources are still existed (#144)





 
Does this answer your question @qianying-99?

**Comment by hickeyma** [comment]
@qianying-99 I am not exactly sure what you are trying to do. 

I will try by explaining as follows. Hope it helps answers. your question.

If you don't need a Helm v2 releases anymore then just delete it from Helm v2 using `helm delete --purge` command. This will however remove the deployed resources in the cluster etc.

If you want to convert over a Helm v2 release to Helm v3 but want to verify afterwards that the conversion worked then `helm 2to3 convert` command maintains the Helm v2 release data. When you are happy with the conversion then you need to delete the Helm v2 release data. This is where the `helm 2to3 cleanup` command is useful. You can use the  `--name` flag for a specific release.

Alternatively, you can remove the Helm v2 release data when running the `helm 2to3 convert` command by using the `--delete-v2-releases` flag.

**Comment by hickeyma** [comment]
@qianying-99 Did this answer your question?

**Comment by hickeyma** [comment]
Going to close this issue due to a lack of feedback. We can re-open if more details provided.
