### ISSUE TITLE
helm3 list does not show my successfully converted release

### ISSUE THREAD

**Issue by ghoben** [helm/helm-2to3#145]
I tried to convert a helm2 release to helm3 with first moving the config. Which worked. After that I tried helm3 2to3 convert <release-name>,which exited properly. 

```
2020/04/27 21:44:16 [Helm 3] Release "my-kubernetes-dashboard" created.
2020/04/27 21:44:16 Release "my-kubernetes-dashboard" was converted successfully from Helm v2 to Helm v3.
2020/04/27 21:44:16 Note: The v2 release information still remains and should be removed to avoid conflicts with the migrated v3 release.
2020/04/27 21:44:16 v2 release information should only be removed using `helm 2to3` cleanup and when all releases have been migrated over.
```

When I issue `helm3 list` though I don't see anything. I still see it in `helm list my-kubernetes-dashboard`.

When i issue the convert command again, it tells me, that it already exists:

```
helm3 2to3 convert my-kubernetes-dashboard
2020/04/27 21:50:23 Release "my-kubernetes-dashboard" will be converted from Helm v2 to Helm v3.
2020/04/27 21:50:23 [Helm 3] Release "my-kubernetes-dashboard" will be created.
2020/04/27 21:50:23 [Helm 3] ReleaseVersion "my-kubernetes-dashboard.v1" will be created.
Error: release: already exists
Error: plugin "2to3" exited with error
```

Any ideas what might be wrong?

**Comment by hickeyma** [comment]
@ghoben Can you see it is you run `helm3 list --all-namespaces`?

**Comment by ghoben** [comment]
Thanks, this was the missing puzzle. I was not aware that helm3 is sensitive to namespaces now in the list command. Thanks @hickeyma

**Comment by hickeyma** [comment]
Yes. Now that Tiller is no longer in Helm, it can save the release metadata in the release namespace. 

For more details, check out the [Helm docs](https://helm.sh/docs/) and a [Helm 3 blog](https://developer.ibm.com/technologies/containers/blogs/kubernetes-helm-3/) I did after Helm 3 release.

**Comment by hickeyma** [comment]
Closing as issue is answered.
