### ISSUE TITLE
Upgrade of Converted Releases Fails

### ISSUE THREAD

**Issue by gsexton** [helm/helm-2to3#147]
Using Helm 3.2.0 and the 0.51 version of the 2to3 converter, I converted some releases from helm 2 to helm 3. 

Now, when I try to upgrade those releases using helm upgrade ... I get the error message:
```
[18458 18208 :007316: nftcx 04/28/2020 20:07:55 -0600 ERROR   ]             
"Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. 
Unable to continue with update: PodSecurityPolicy "common-services-grafana" in 
namespace "" exists and cannot be imported into the current release: invalid 
ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": 
must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": 
must be set to "common-services"; annotation validation error: missing key 
"meta.helm.sh/release-namespace": must be set to "default"
```
So it looks like the upgrade is failing because helm 3 expects some annotations to be present that the converter isn't creating. Is that a good analysis?

Is there any way to get the converter to add these keys?

Thanks.

George

**Comment by hickeyma** [comment]
@gsexton Thanks for raising the issue.

To help me reproduce this issue would you have a chart that was used to create the last version of the release in Helm v2? This will help me to troubleshoot and identify the issue.

**Comment by rimusz** [comment]
@gsexton can you try to install that chart with helm v3 and then do the upgrade?

**Comment by gsexton** [comment]
@rimusz The base chart version won't install using helm 3. I'm getting errors

Error: UPGRADE FAILED: rendered manifests contain a resource that already 
exists. Unable to continue with update: PodSecurityPolicy "common-services-grafana" 
in namespace "" exists and cannot be imported into the current release: invalid 
ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": 
must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": 
must be set to "common-services"; annotation validation error: missing key 
"meta.helm.sh/release-namespace": must be set to "default"

[13016 84672 :020874: nftcx 05/08/2020 13:51:21 -0600 ERROR   ]             
```

Error: unable to build kubernetes objects from release manifest: 
[unable to recognize "": no matches for kind "Alertmanager" in version 
"monitoring.coreos.com/v1", unable to recognize "": no matches for kind 
"Prometheus" in version "monitoring.coreos.com/v1", unable to recognize 
"": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", 
unable to recognize "": no matches for kind "ServiceMonitor" in version 
"monitoring.coreos.com/v1"]
```

**Comment by gsexton** [comment]
@hickeyma Thanks for your response. I apologize for the delay in coming back to this.

I tried creating a simple test case, and it works as expected. Here's some additional information. I dumped the PodSecurityPolicy that's erroring out during the upgrade. Here's the version of the original chart AFTER upgrade to Helm 3:

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  creationTimestamp: "2020-05-07T00:03:39Z"
  labels:
    app: grafana
    chart: grafana-3.3.9
    heritage: Tiller
    release: common-services
  name: common-services-grafana
  resourceVersion: "6461"
```
Here's what it looked like on another cluster where it was installed via helm 3

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: common-services
    meta.helm.sh/release-namespace: default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  creationTimestamp: "2020-05-08T13:29:52Z"
  labels:
    app: grafana
    app.kubernetes.io/managed-by: Helm
    chart: grafana-3.3.9
    heritage: Helm
    release: common-services
  name: common-services-grafana
  resourceVersion: "240767"
```
And here's the error message when the helm upgrade command is executed.

```
Error: UPGRADE FAILED: rendered manifests contain a resource that already 
exists. Unable to continue with update: PodSecurityPolicy "common-services-grafana" 
in namespace "" exists and cannot be imported into the current release: invalid 
ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": 
must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": 
must be set to "common-services"; annotation validation error: missing key 
"meta.helm.sh/release-namespace": must be set to "default"
```
I looked through the source code for the converter, and it looks like it's just copying the existing helm 2 annotations.

I diffed the grafana chart, and can see where the PodSecurityPolicy APIVersion has updated.

```
+++ common-services-1.1.91871/common-services/charts/prometheus-operator/charts/grafana/templates/podsecuritypolicy.yaml        2020-05-08 09:17:56.000000000 -0600
@@ -1,7 +1,7 @@
 {{- if .Values.rbac.pspEnabled }}
-apiVersion: extensions/v1beta1
+apiVersion: policy/v1beta1
 kind: PodSecurityPolicy
```

So, it looks to me like the issue here is that the API version has changed, and Helm 3 is trying to reconcile ownership using the additional metadata annotations, but they're not present.

Does that sound right to you?

Do you see a way forward?

**Comment by kiyutink** [comment]
We're encountering the same issue with a release of nginx-ingress. We tried to manually change missing labels / annotations, but encountered the following problem:
```
cannot patch "nginx-ingress-controller-default-backend" with kind Deployment: Deployment.apps "nginx-ingress-controller-default-backend" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"nginx-ingress", "release":"nginx-ingress-controller", "app.kubernetes.io/component":"default-backend"}: `selector` does not match template `labels`
```

I'm quite new to helm and k8s in general, would be grateful if someone could decypher it for me

**Comment by gsexton** [comment]
@kiyutink We ran into something similar. In our case, there was a StatefulSet that didn't have a selector defined at the template. Kubernetes/Helm supplied a default selector that matched all labels. In our case, what I did was write a little script to patch the set of selector labels to be the release and namespace. I then set the StatefulSet's template selector to match. Once I did that, I could upgrade.

Start by looking at your deployment with 'kubectl get deployment <name> -o yaml' and examine the selector. Then, look at your chart's.

**Comment by hickeyma** [comment]
There are a few things at play here and will try to answer them one by one.

> The base chart version won't install using helm 3. I'm getting errors
[13016 84672 :020874: nftcx 05/08/2020 13:51:21 -0600 ERROR   ]             
```
Error: unable to build kubernetes objects from release manifest: 
[unable to recognize "": no matches for kind "Alertmanager" in version 
"monitoring.coreos.com/v1", unable to recognize "": no matches for kind 
"Prometheus" in version "monitoring.coreos.com/v1", unable to recognize 
"": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", 
unable to recognize "": no matches for kind "ServiceMonitor" in version 
"monitoring.coreos.com/v1"]
```

This looks like an issue whereby the chart template is using a removed Kubernetes API `monitoring.coreos.com/v1` for the Kubernetes version that it is been deployed on. It would seem that the API is being used for kind: `Alertmanager`, `Prometheus` and `ServiceMonitor`.

The chart would need to be updated to a support Kubernetes API for the Kubernetes version that you are installing on. See [Deprecated Kubernetes APIs](https://helm.sh/docs/topics/kubernetes_apis/) for more details.

**Comment by hickeyma** [comment]
> I looked through the source code for the converter, and it looks like it's just copying the existing helm 2 annotations.

That should be ok as it it is dependent on the annotations defined in the chart. If specific annotations are now required in a Kubernetes version for a kind then the Helm v2 release should be upgraded first with the modified annotation before conversion. 

> So, it looks to me like the issue here is that the API version has changed, and Helm 3 is trying to reconcile ownership using the additional metadata annotations, but they're not present.

This is probably the Kubernetes cluster and not Helm.

> I diffed the grafana chart, and can see where the PodSecurityPolicy APIVersion has updated.
```
+++ common-services-1.1.91871/common-services/charts/prometheus-operator/charts/grafana/templates/podsecuritypolicy.yaml        2020-05-08 09:17:56.000000000 -0600
@@ -1,7 +1,7 @@
 {{- if .Values.rbac.pspEnabled }}
-apiVersion: extensions/v1beta1
+apiVersion: policy/v1beta1
 kind: PodSecurityPolicy
```

This diff signifies that `PodSecurityPolicy` should use the supported API `policy/v1beta1` as `extensions/v1beta1` is now deprecated/removed for this kind. This is similar to https://github.com/helm/helm-2to3/issues/147#issuecomment-630939900 where would need to update you release to supported API prior to migrating the release to v3 or upgrading cluster.

> app.kubernetes.io/managed-by label

This is set to `Tiller` in Helm v2 and when migrated it will remain the same. When you upgrade a release in Helm v3 it updates it to `Helm`. All labels and annotations are part of the manifest blob and are just mapped over as is. Helm should be able to handle it and updates it to v3 properties during an upgrade.

**Comment by hickeyma** [comment]
@gsexton @kiyutink I hope the above comments provide some feedback to your questions and issues.

To be able to identify an issue with the conversion and Helm upgrade, I would need to get a way to repeat the issues. On good way to do this would be to:
1. Get the chart which was the last install/upgrade of a v2 release
2. Do a `helm install` using Helm v3 and this chart into the cluster where the Helm upgrade is failing for the release that you converted
3. Show the results 

This would help me better troubleshoot this.

**Comment by hickeyma** [comment]
With regard to:
- meta.helm.sh/release-name: <RELEASE_NAME>
- meta.helm.sh/release-namespace: <RELEASE_NAMESPACE>

They can be used for adopting existing already created resources and are not mandatory in Helm templates (https://github.com/helm/helm/pull/7649).

**Comment by gsexton** [comment]
> 
> 
> There are a few things at play here and will try to answer them one by one.
> 
> > The base chart version won't install using helm 3. I'm getting errors
> > [13016 84672 :020874: nftcx 05/08/2020 13:51:21 -0600 ERROR   ]
> 
> ```
> Error: unable to build kubernetes objects from release manifest: 
> [unable to recognize "": no matches for kind "Alertmanager" in version 
> "monitoring.coreos.com/v1", unable to recognize "": no matches for kind 
> "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize 
> "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", 
> unable to recognize "": no matches for kind "ServiceMonitor" in version 
> "monitoring.coreos.com/v1"]
> ```
> 
> This looks like an issue whereby the chart template is using a removed Kubernetes API `monitoring.coreos.com/v1` for the Kubernetes version that it is been deployed on. It would seem that the API is being used for kind: `Alertmanager`, `Prometheus` and `ServiceMonitor`.
> 
The issue here was actually CRDs. The reason the chart couldn't install with helm 2 is because they had been created in the CRDs directory.

**Comment by hickeyma** [comment]
> The issue here was actually CRDs. The reason the chart couldn't install with helm 2 is because they had been created in the CRDs directory.

Ok, good to know @gsexton. It is very interesting to try and troubleshoot different users environment and build up an understanding of what happens. Thanks for sharing.

For reference, CRDs differ in execution in Helm 3: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by dza89** [comment]
Anyone experiencing the original issue:

1. Upgrade helm itself to the latest version (3.2.1) and do not upgrade the helm chart itself.
2. Upgrade your helm chart with changes.

**Comment by hickeyma** [comment]
@dza89 Do you mind raising a new issue and add the steps to reproduce? This will help better troubleshoot the issue.

**Comment by dza89** [comment]
@hickeyma 
If you want I'm fine with it, but this the exact the original issue.
The problem lies in changes in your helm chart and changes to helm version at the same time.

Helm should:
1. Apply new annotations
2. Make changes as defined in your helm chart

Helm is:
1. Trying to make changes in your helm chart
b. Breaking because it cannot validate the missing annotations.

**Comment by hickeyma** [comment]
@dza89 It would be better raise a new issue and provide more details. I would need to know the steps using a chart as an example through the different steps when first deployed using v2, the migration of that release and then the upgrade in v3 and where/how it fails.

**Comment by Hashfyre** [comment]
I have the same issue trying to test out `stable/prometheus-operator` locally (testing a fork for a future PR, no code committed yet)
```
helm install my-release .
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: 
  CustomResourceDefinition "alertmanagers.monitoring.coreos.com" in namespace "" exists and cannot be imported into the current release: 
  invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
  annotation validation error: missing key "meta.helm.sh/release-name": must be set to "my-release"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "<namespace>"
```
```
# helm history my-release
Error: release: not found   
```
@hickeyma I can report this as a fresh issue if you want. Just putting it here for posterity.

**Comment by hickeyma** [comment]
@Hashfyre A new issue with be great, thanks

**Comment by AbhinayGupta741** [comment]
Hello everyone,

I was facing exact same issue after updating the helm version from  2 to 3.
I was able to resolve this by purging the old helm deployment.
helm delete <name> --purge
Then I was able to upgrade the services with helm upgrade successfully.

I hope it helps someone!

**Comment by hickeyma** [comment]
@AbhinayGupta741 This is a destructive approach whereby when you do a `helm delete --purge` on the Helm v2 release, it will remove it and all the Kubernetes resources associated. This then leave the Helm v3 release with Helm metadata only and no Kubernetes resources associated. The upgrade will work alright but would only recommend this as a last resource.

When you say you have the exact same issue, it would be better then to follow the feedback in the comments of the issue. The symptom showing here is "cannot upgrade". This is however related to a number of issues which needed to be resolved so that could continue.

**Comment by bcollard** [comment]
this helped me, with a broken upgrade process on the `prometheus-operator` helm chart, after migration with helm-2to3:

```
kubectl -n monitoring label ingress -l "heritage=Tiller" "app.kubernetes.io/managed-by=Helm"
kubectl -n monitoring annotate ingress -l "heritage=Tiller" "meta.helm.sh/release-name=prometheus-operator" "meta.helm.sh/release-namespace=monitoring"
```

**Comment by abdennour** [comment]
thank you @bcollard ! same thing happen when trying to upgrade vault-operator

**Comment by vcorr** [comment]
I have the same problem. After running the conversion for my release I tried upgrading it with --dry-run flag, but I got the error:

`Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: Deployment "xyz" in namespace "xxx" exists and cannot be imported into the current release: invalid ownership metadata; 
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "abc"; 
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "xxx"`

I added the missing annotations and fixed the label and sure enough, that error was gone, but then I got the same error on the next object...after fixing each and every Kubernetes object in the release with the same annotations and label the upgrade finally worked. Is there anyway to automate this? I still have a pile of releases to convert and upgrade.

**Comment by vcorr** [comment]
I found one way to reduce the work at least. You can set the label and annotations with kubectl:

`kubectl -n xxx annotate --overwrite --all Deployment  meta.helm.sh/release-name=xxx`

This could be further improved of course by making a script that fetches all the objects in the release and fixes them all, but it's still a hack.
I'm still interested to know if there is a better way for this!

**Comment by hickeyma** [comment]
@vcorr Added some background in https://github.com/helm/helm-2to3/issues/162#issuecomment-682581264. Hope this helps shed some light on your issue.

**Comment by leelanakka** [comment]
HI @hickeyma ,

I'm getting the similar kind of issue please tell me the solution for it.
 ````
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: ServiceMonitor "monitor" in namespace "nha-app" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "monitor"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "nha-app"

````

**Comment by DeirdreRodgers** [comment]
I've had a similar issue but my situation might be a little different. I deleted and purged a helm2 chart and reployed as helm3 and I ran into this issue. We solved it my checking the deployment associated with the helm. It hadnt been deleted for some reason when we did a helm delete --purge. Once we deleted it and redeployed we had no issues. Maybe this might help some people

**Comment by archi144** [comment]
I've had a same issue. After migration from Helm2 to Helm3 my new manifests included new api version of ingress. And helm3 raise a error:
_Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Ingress "test-ingress" in namespace "helm-migration-experiments" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "test-helm-migration-release"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "helm-migration-experiments"_

I did these steps and i was able to upgrade my release:

1. Wrote previous working api version in the ingress manifest 
2. Deployed it
3. Got success, then i wrote new api version into ingress manifest
4. Deployed it and i've got the success deploy.
