### ISSUE TITLE
how to install from downloaded binaries

### ISSUE THREAD

**Issue by nemoo** [helm/helm-2to3#148]
This is not a defect, but a usage question:

I am trying to install the 2to3 plugin in a linux docker image via the downloaded https://github.com/helm/helm-2to3/releases/download/v0.5.1/helm-2to3_0.5.1_linux_amd64.tar.gz

When I untar the binary into a tmp directory and try the installation via `helm3 plugin install /tmp/helm-2to3`,  it still tries to download from github. 

Is there a way to perform the installation of the plugin just locally, without it trying to download something from the internet?

**Comment by hickeyma** [comment]
@nemoo The `helm plugin install` command calls the [install plugin script](https://github.com/helm/helm-2to3/blob/master/scripts/install_plugin.sh) which downloads from the repo.

If you want to avoid this you can just copy the extracted plugin directory from the tarball to ${HOME}/.local/share/helm/plugins/. It should then show when you run `helm plugin list`.

**Comment by nemoo** [comment]
thanks a lot for the hint!

I untared the content of the tar file into a folder ${HOME}/.local/share/helm/plugins/2to3
```
[cloudman@c409f9587b31 2to3]$ pwd
/home/cloudman/.local/share/helm/plugins/2to3
[cloudman@c409f9587b31 2to3]$ ls
2to3  LICENSE  README.md  completion.yaml  plugin.yaml  scripts

```

That results in helm displaying it as a plugin:

```
[cloudman@c409f9587b31 ~]$ helm3 plugin list
NAME	VERSION	DESCRIPTION                                                               
2to3	0.5.1  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

Yet, when I try to use it, I get this error:

```
[cloudman@c409f9587b31 ~]$ helm3 2to3 convert --dry-run --tiller-ns env-tiller env-pipetest
Error: fork/exec /home/cloudman/.local/share/helm/plugins/2to3/bin/2to3: no such file or directory
```
Any idea what I am still doing wrong?

**Comment by nemoo** [comment]
So the plugins.yaml expected the script under plugins/<pluginname>/bin/2to3. So I also copied it there. now it works. 
Cheers!

**Comment by hickeyma** [comment]
@nemoo That's correct, the binary needs to be in the `bin` sub-directory. Sorry but forgot to add that in my previous comment.

I'm glad that it is now working for you.

**Comment by srinivasev** [comment]
Hi @hickeyma ,
I don't have this directory in my container.
`${HOME}/.local/share/helm/plugins/`

We are making use of helm like below - 
```
wget https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz
ADD --chown=7777 ./linux-amd64/* /opt/ood/config/be/cbnfvo/Kubernetes_1.1.0/helm/
```

Where should the plugins directory be extracted in this case?

**Comment by hickeyma** [comment]
@srinivasev  create the directory and follow steps in https://github.com/helm/helm-2to3/issues/148#issuecomment-630780203

**Comment by srinivasev** [comment]
Hi @hickeyma ,

I tried the same in my container. its not listing for me,

![image](https://user-images.githubusercontent.com/11441751/143233303-ec839c2d-37bc-4ff4-9759-bb2da9e179b6.png)

**Comment by srinivasev** [comment]
Hi @hickeyma ,

Thanks, now it is listing the plugin.

Can you please let me know what additional thing to check here? From the above comments, I didn't understand what has to be done for this error.

![image](https://user-images.githubusercontent.com/11441751/143235286-4fdda2ab-37cf-418b-8ace-5d4a4b96d6da.png)

**Comment by hickeyma** [comment]
That should be it. Have a look at [Helm Plugins](https://helm.sh/docs/topics/plugins/) docs for more details.

**Comment by srinivasev** [comment]
Hi @hickeyma ,

I am able to place the 2to3 plugin in respective folders successfully and invoke the convert command.

But facing below error, what could be the reason ?

`/opt/ood/config/be/cbnfvo/Kubernetes_1.1.0/helm/helm 2to3 convert helloworldhelm3 --namespace="cnfdeployments" error message: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/9026c1e4-5773-4f53-a73a-fc3f18bf4313/kube_config.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/9026c1e4-5773-4f53-a73a-fc3f18bf4313/kube_config.yaml
2021/11/25 04:39:55 Release "helloworldhelm3" will be converted from Helm v2 to Helm v3.
2021/11/25 04:39:55 [Helm 3] Release "helloworldhelm3" will be created.
2021/11/25 04:39:55 Get "https://10.93.48.241:8082/proxy/apiserver/api/v1/namespaces/kube-system/pods?labelSelector=name%3Dtiller": Forbidden
Error: plugin "2to3" exited with error)`

**Comment by srinivasev** [comment]
Hi, 
Its working fine now.

The forbidden issue is because I have a proxy set in my docker file. Removing that resolved the issue.
