### ISSUE TITLE
Local Developer Install

### ISSUE THREAD

**Issue by pretzelmaker** [helm/helm-2to3#150]
When using the instructions provided for installing a locally built binary for use with helm v2, it continues to use the remote binaries.

```bash
$ helm plugin install ~/go/src/github.com/helm/helm-2to3
Downloading and installing helm-2to3 v0.5.1 ...
https://github.com/helm/helm-2to3/releases/download/v0.5.1/helm-2to3_0.5.1_darwin_amd64.tar.gz
Installed plugin: 2to3
```

**Comment by hickeyma** [comment]
Thanks for raising this @pretzelmaker.

You are correct in observing that the `plugin install` will call the script 
The [Developer Install](https://github.com/helm/helm-2to3#developer-from-source-install) section needs to be updated as follows:
- `make build` --> `make`
- Mention that you can run the binary directly as: `./bin/2to3`
- Or if want to run as plugin, copy the `helm-2to3` directory to the [Helm data path](https://helm.sh/docs/faq/#xdg-base-directory-support) (`~/.local/share/helm/plugins/` by default)

**Comment by hickeyma** [comment]
@pretzelmaker Feel free to push a PR if you like.

**Comment by hickeyma** [comment]
@pretzelmaker I just saw that you pushed PR #151. Thanks for this.  I think the fix you pushed covers the issue and no need for all the points I raised in https://github.com/helm/helm-2to3/issues/150#issuecomment-639344290.

**Comment by pretzelmaker** [comment]
@hickeyma - Thanks for reviewing and accepting the PR
