### ISSUE TITLE
Is there a way to bypass 2to3 confirm ?

### ISSUE THREAD

**Issue by digeler** [helm/helm-2to3#158]
we are using the helm 2to3 convert grammatically in c# ,is there a way to bypass this confirmation : 
> helm3 2to3 move config
2020/07/29 10:50:21 WARNING: Helm v3 configuration may be overwritten during this operation.
2020/07/29 10:50:21
[Move Config/confirm] Are you sure you w**ant to move the v2 configuration? [y/N]:**

we are using the c# start process : 
 new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "helm3",
                        Arguments = $"{arguments}",
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        CreateNoWindow = true,
                        UseShellExecute = false
                    }
                };
what will be the best way to send yes ,or to bypass this message ?
thank you.

**Comment by rimusz** [comment]
use `yes | helm3 2to3 move config`

**Comment by digeler** [comment]
Thanks ,but am already running the process 
StartInfo = new ProcessStartInfo
{
FileName = "helm3",
is there any other solution ,isnt there a parameter or a flag.

**Comment by rimusz** [comment]
no, there is no other solution

**Comment by digeler** [comment]
this does not work either :
![image](https://user-images.githubusercontent.com/4949529/88782369-2daf8a80-d196-11ea-8ea2-9048dbe598cd.png)

**Comment by rimusz** [comment]
it works in bash:
```
$ yes | helm3 2to3 move config --dry-run
2020/07/29 12:24:49 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/29 12:24:49 Run without --dry-run to take the actions described below:
2020/07/29 12:24:49
2020/07/29 12:24:49 WARNING: Helm v3 configuration may be overwritten during this operation.
2020/07/29 12:24:49
[Move Config/confirm] Are you sure you want to move the v2 configuration? [y/N]: 2020/07/29 12:24:49
Helm v2 configuration will be moved to Helm v3 configuration.
2020/07/29 12:24:49 [Helm 2] Home directory: /Users/rimas/.helm
2020/07/29 12:24:49 [Helm 3] Config directory: /Users/rimas/Library/Preferences/helm
2020/07/29 12:24:49 [Helm 3] Data directory: /Users/rimas/Library/helm
2020/07/29 12:24:49 [Helm 3] Cache directory: /Users/rimas/Library/Caches/helm
2020/07/29 12:24:49 [Helm 3] Create config folder "/Users/rimas/Library/Preferences/helm" .
2020/07/29 12:24:49 [Helm 2] repositories file "/Users/rimas/.helm/repository/repositories.yaml" will copy to [Helm 3] config folder "/Users/rimas/Library/Preferences/helm/repositories.yaml" .
2020/07/29 12:24:49 [Helm 3] Create cache folder "/Users/rimas/Library/Caches/helm" .
2020/07/29 12:24:49 [Helm 3] Create data folder "/Users/rimas/Library/helm" .
2020/07/29 12:24:49 [Helm 2] plugins "/Users/rimas/.helm/cache/plugins" will copy to [Helm 3] cache folder "/Users/rimasm/Library/Caches/helm/plugins" .
2020/07/29 12:24:49 [Helm 2] plugin symbolic links "/Users/rimas/.helm/plugins" will copy to [Helm 3] data folder "/Users/rimasm/Library/helm" .
2020/07/29 12:24:49 [Helm 2] starters "/Users/rimas/.helm/starters" will copy to [Helm 3] data folder "/Users/rimas/Library/helm/starters" .
```
Sorry not familiar with Windows doing such stuff as passing `yes` to the command.

What's your use case that you even want to automate helm config move?

**Comment by digeler** [comment]
its a part of our automated code ,for multiple env 
we also planing to automate the convert also.
the base os is windows

**Comment by digeler** [comment]
tried git bash also no luck on windows : 
![image](https://user-images.githubusercontent.com/4949529/88784918-3f466180-d199-11ea-834a-b98d98fd0f45.png)

**Comment by rimusz** [comment]
sorry cannot help much when it comes to Windowz

**Comment by digeler** [comment]
can someone from the community help me with this please , is the a way to add a flag to by pass it ?
thanks

**Comment by hickeyma** [comment]
@digeler Something similar was added for the cleanup command in #154. Would you like to push a PR for it?

**Comment by digeler** [comment]
i can sure try ,ill let you know once am done , thanks

**Comment by digeler** [comment]
https://github.com/helm/helm-2to3/pull/159

**Comment by digeler** [comment]
@hickeyma can you you or a maintainer approve the pr above please

**Comment by hickeyma** [comment]
@digeler I have reviewed the pr and comments provided. Update when you get a chance.
