### ISSUE TITLE
Found 0 tiller pods , Error: plugin "2to3" exited with error

### ISSUE THREAD

**Issue by pc-rnukala1** [helm/helm-2to3#160]
I am trying to migrate an app from helm2 to helm3 and following the steps mentioned - https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/ and i get the below error. Can you please help me here

helm3 2to3 convert test-service -n test-app
2020/08/03 22:45:38 Release "test-service" will be converted from Helm v2 to Helm v3.
2020/08/03 22:45:38 [Helm 3] Release "test-service" will be created.
2020/08/03 22:45:39 Found 0 tiller pods
Error: plugin "2to3" exited with error

**Comment by hickeyma** [comment]
@pc-rnukala1 This error implies that your Helm v2 does not have a Tiller instance running in the cluster. Are you using [Tillerless Helm](https://github.com/rimusz/helm-tiller)?

**Comment by pc-rnukala1** [comment]
@hickeyma - we have the tiller running too

$kubectl get pods -n tiller-system
NAME                            READY   STATUS    RESTARTS   AGE
tiller-deploy-89cbccbb9-n2r26   1/1     Running   0          14d

**Comment by hickeyma** [comment]
@pc-rnukala1 If you Tiller namespace is `tiller-system`, then pass this using the ` -t, --tiller-ns` flag.

Can you try running this instead: `helm3 2to3 convert test-service -t  tiller-system`

**Comment by hickeyma** [comment]
Ant progress on this @pc-rnukala1

**Comment by pc-rnukala1** [comment]
@hickeyma - thats working, Thanks for the reply.
