### ISSUE TITLE
Add Docker authentication to CircleCI jobs

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-2to3#166]
Starting November 1, 2020, Docker Hub will impose rate limits based on the originating IP. Since CircleCI runs jobs from a shared pool of IPs, it is highly recommended to use authenticated Docker pulls with Docker Hub to avoid rate limit problems.

More information on how to apply authentication to CI jobs can be found here: https://circleci.com/docs/2.0/private-images/

https://github.com/helm/helm-2to3/blob/a401afdaf68988202bdeda1707fd8a5271ff2067/.circleci/config.yml#L5
https://github.com/helm/helm-2to3/blob/a401afdaf68988202bdeda1707fd8a5271ff2067/.circleci/config.yml#L15
https://github.com/helm/helm-2to3/blob/a401afdaf68988202bdeda1707fd8a5271ff2067/.circleci/config.yml#L22

See https://github.com/helm/helm/issues/8848

**Comment by rimusz** [comment]
@bacongobbler do we docker hub user in Helm org which we could use there?

**Comment by bacongobbler** [comment]
There is a helm user account available for the helm project itself. @hickeyma should be able to access and use those credentials.

See https://github.com/helm/helm/pull/8887.
