### ISSUE TITLE
helm3 convert error

### ISSUE THREAD

**Issue by Ruifeng-Wu** [helm/helm-2to3#168]
<img width="836" alt="xx" src="https://user-images.githubusercontent.com/25561978/97519808-c98aa580-19d4-11eb-869f-b774df92d55f.png">

The first few steps succeeded, but failed at the conversion.

**Comment by marckhouzam** [comment]
Do you actually have a release named `RELEASE` on your cluster?  Normally you would replace the word `RELEASE` with an real release name.

**Comment by hickeyma** [comment]
Ping @Ruifeng-Wu, any more details on this issue?

**Comment by hickeyma** [comment]
Closing this as no response. Can re-open if needed.
