### ISSUE TITLE
helm 2to3 cleanup creates many client instances per release

### ISSUE THREAD

**Issue by sarahhodne** [helm/helm-2to3#175]
I just ran `helm 2to3 cleanup` against an EKS cluster, where the kubeconfig contains an exec auth config, and got this line about 80 times per ReleaseVersion that was deleted:

```
W1214 22:15:35.966217   52131 exec.go:203] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 74866 clients constructed calling "saml2aws"
```

(with the number near the end incrementing for every time the line was outputted)

This is probably fine, but a bit inefficient and makes the logs from `helm 2to3 cleanup` very difficult to read, since they are full of these log entries.

**Comment by bacongobbler** [comment]
We've discovered this issue in helm/helm a while back as well. It was attributed to a pkg/kube recreating the clientset each call to Kubernetes.

See https://github.com/helm/helm/issues/8854 and the fix at https://github.com/helm/helm/pull/8855 for more context.

If helm-2to3 is using the same client packages, it may be worth updating to Helm 3.4.1 to receive the fix.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-2to3/blob/33c73b1dc51983dd318fcd74f4eff8b2d473a88b/go.mod#L14

**Comment by hickeyma** [comment]
@sarahhodne Thanks for raising the issue.

@bacongobbler Thanks for the feedback. Have pushed PR #176.
