### ISSUE TITLE
helm chart linting

### ISSUE THREAD

**Issue by gitkent** [helm/helm-2to3#177]
Hi all,

We have multiple applications with chart created from helm2 client. We are recently migrating to Helm3. As part of the deployment, we doing helm linting but it seems it is not happy when the chart doesn't has `spec.selector.matchExpression`. for e.g.

```
11:01:01  + helm lint ./helm/charts/my-app
11:01:01  ==> Linting ./helm/charts/my-app
11:01:01  [INFO] Chart.yaml: icon is recommended
11:01:01  [ERROR] templates/deployment.yaml: a Deployment must contain matchLabels or matchExpressions, and "test-release-my-app" does not
11:01:01  
11:01:01  Error: 1 chart(s) linted, 1 chart(s) failed
```

I understand that this new linting rule (https://github.com/helm/helm/pull/8142) has been added that comes with Helm3. We have added the matchLabels into one chart and it fixed the issue. 

Q: is there any other way/tool that we can use to inserting this required fields into a chart? or we just have to continue doing it manually or write our own script?

**Comment by rimusz** [comment]
I'm not aware of any tool which can insert these required fields into charts.

**Comment by hickeyma** [comment]
@gitkent I would think the best approach would be to just update the relevant file(s) in your charts. As @rimusz said not sure there is a tool available for this.

Let us know if you are able to progress.

**Comment by hickeyma** [comment]
@gitkent Any update on this?

**Comment by gitkent** [comment]
@hickeyma All good. We'd been updating chart manually for now.
