### ISSUE TITLE
Ok to delete tiller serviceaccount, clusterrolebinding and namespace 

### ISSUE THREAD

**Issue by nodesocket** [helm/helm-2to3#186]
Ran through the migration and everything worked great. Noticed that the `tiller` Kubernetes namespace, `serviceaccount`, and `clusterrolebindings` are still left orphaned though. Is it safe to remove these?

```
kubectl delete clusterrolebinding tiller-cluster-role
kubectl delete serviceaccount tiller --namespace tiller
kubectl delete namespace tiller
```

**Comment by marckhouzam** [comment]
Yes, I removed them manually at the end of my migrations.
