### ISSUE TITLE
Modify release-versions-max after migrating cluster from 2 to 3

### ISSUE THREAD

**Issue by nodesocket** [helm/helm-2to3#187]
I used the plugin `2to3` to migrate a Helm 2 to Helm 3 deployment.

```
helm3 2to3 convert --release-versions-max 250 --tiller-ns tiller <release-name>
```

The problem is now my secrets are filled with chart release versions. Is there a way to modify `release-versions-max` after the fact? I'd like to reduce this to a more manageable `10` for all charts.

**Comment by hickeyma** [comment]
@nodesocket Sorry to hear that you converted over more release versions than you intended. FYI, if you don't specify `--release-versions-max` it defaults to 10.

The way to do this is remove the secret corresponding to the chart release versions you don't want. This should be done with the oldest (i.e.  smallest version number) and in a consecutive block (i.e. don't remove versions in an adhoc fashion).

You can use this command to get the secret names in your cluster:
`kubectl get secret -l owner=helm,name=<release_name> --namespace <release_namespace> | awk '{print $1}' | grep -v NAME`

An example is where I want to remove chart version 1 and 2 of release `mychart` in namespace `test-ns`:

```console
$ helm ls -n test-ns
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
mychart	test-ns  	3       	2021-05-06 12:00:53.103031 +0100 IST	deployed	mychart-0.1.0	1.16.0  

$ kubectl get secret -l owner=helm,name=mychart --namespace test-ns | awk '{print $1}' | grep -v NAME 
sh.helm.release.v1.mychart.v1
sh.helm.release.v1.mychart.v2
sh.helm.release.v1.mychart.v3

$ kubectl delete secrets sh.helm.release.v1.mychart.v1 sh.helm.release.v1.mychart.v2 -n test-ns 
secret "sh.helm.release.v1.mychart.v1" deleted
secret "sh.helm.release.v1.mychart.v2" deleted

$ helm history mychart -n test-ns 
REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	DESCRIPTION     
3       	Thu May  6 12:00:53 2021	deployed	mychart-0.1.0	1.16.0     	Upgrade complete
```

Let me know if this worked.

**Comment by hickeyma** [comment]
@nodesocket yes, it will convert the latest number of release versions as per the max value.

**Comment by nodesocket** [comment]
@hickeyma thanks so much.
