### ISSUE TITLE
Add cleanup feature

### ISSUE THREAD

**Issue by rimusz** [helm/helm-2to3#19]
- cleanup home (delete .helm folder)
- cleanup releases (delete tiller releases)
- uninstall Tiller

By default `--dry-run` is set, so no cleanup can be done without providing `--disable-dry-run` flag.
We do not want users by mistake to run the full clean up.

**Comment by hickeyma** [comment]
@rimusz Small change on the proposal in the description:

> By default --dry-run is set, so no cleanup can be done without providing --disable-dry-run flag.

It is not set by default. There is however a warning on the changes and also a confirmation question if the use wants to proceed as follows:

```console
$ helm 2to3 cleanup
WARNING: Helm v2 Configuration, Release Data and Tiller Deployment will be removed.
This will clean up all releases managed by Helm v2. It will not be possible to restore them if you haven't made a backup of the releases.
Helm v2 will not be usable afterwards.

[Cleanup/confirm] Are you sure you want to cleanup Helm v2 data? [y/N]: 
```

**Comment by rimusz** [comment]
The warning works very well 👍
