### ISSUE TITLE
Error: RELEASE_NAME has no deployed releases

### ISSUE THREAD

**Issue by jackiig** [helm/helm-2to3#192]
Attempting to upgrade a Gitlab managed cluster from helm2 to helm3.  Way late to the party on this change, unfortunately.

Thanks to the other Issues I found on Github, I have tried to check which namespace the config is in (`redirect`, which is also the current namespace in `kubeconfig`) from Issue #136.  I also added `--tiller-ns` to the  command per Issue #97, and checked where the `--release-storage` was set to.

```sh
$ HELM_HOST=localhost:44134 helm2 version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"[sic]", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"[sic]", GitTreeState:"clean"}
$ HELM_HOST=localhost:44134 helm3 version
version.BuildInfo{Version:"v3.6.0", GitCommit:"[sic]", GitTreeState:"dirty", GoVersion:"go1.16.4"}
$ TILLER_NAMESPACE=redirect tiller listen localhost:44134 -alsologtostderr &
$ HELM_HOST=localhost:44134 helm2 ls
NAME      	REVISION	UPDATED                 	STATUS  	CHART                APP VERSION	NAMESPACE
production	122     	Sat Jun  5 21:09:07 2021	DEPLOYED	auto-deploy-app-1.0.7           	redirect
$ HELM_HOST=localhost:44134 helm3 list
# Nothing listed.
$ kubectl get secrets -n redirect -l OWNER=TILLER
No resources found in redirect namespace.
 $ kubectl get configmaps -n redirect -l OWNER=TILLER
NAME              DATA   AGE
production.v1     1      672d
[~120 releases]
$ kubectl get po -n gitlab-managed-apps | grep tiller
tiller-deploy-5c85978967-wchq5                           1/1     Running   0          3d17h
$ HELM_HOST=localhost:44134 helm3 2to3 convert --dry-run --tiller-ns=gitlab-managed-apps production
[sic]
Release "production" will be converted from Helm v2 to Helm v3.
[Helm 3] Release "production" will be created.
Error: production has no deployed releases
```

At this point I'm stumped.  `helm2` seems to see the release just fine.  `2to3` seems to be completely missing it.

Thank you in advance for any help.

--

Possible duplicate of:

- Got Error: RELEASE_NAME has no deployed releases #97
- RELEASE_NAME has no deployed releases #136

**Comment by hickeyma** [comment]
@jackiig Looks like you are using Tiller outside of the cluster for Helm 2, similar to Tillerless. But you also running Tiller in the cluster. Might get bit confusing! :)

The Tiller namespace also seems to be `redirect` as that is where the `production` release data is stored. Helm 2 stores the release data in the Tiller namespace. Helm 3 stores it in the namespace of the release.

Assuming you want to use the local/outside of Tiller instance, what is the output from the following command: `helm3 2to3 convert --dry-run --tiller-out-cluster --release-storage=configmaps --tiller-ns=redirect production`?

**Comment by jackiig** [comment]
@hickeyma You are a rockstar.  Thank you.  I think I had tried most of those, just not together.  

Thank you, thank you, thank you.
