### ISSUE TITLE
helm2 lists the migrated releases

### ISSUE THREAD

**Issue by srinivasev** [helm/helm-2to3#196]
Hi @hickeyma ,

This is a support/information question.

Is there an option to show only helm2 releases which are undergone migration yet to helm3?.

I have a use case where I need to display both helm2 and helm3 releases in a namespace. I am currently running 2 commands from my code - 
helm list --kubeconfig /tmp/kube.yaml --output json
helm3 list --kubeconfig /tmp/kube.yaml --output json

As helm2 list command and helm3 list command list same releases in case of migrated helm releases, it is leading to duplicates for the UI response.

**Comment by hickeyma** [comment]
When you migrate a release and you are happy it is migrated as expected, you can remove that release from v2 with following command: `helm 2to3 cleanup --release-cleanup --name <release_name>`.  Then the migrated release is only visible by v3.

**Comment by srinivasev** [comment]
As this is performed in the customer environment, I am not supposed to perform any cleanup activity. I found this in the documentation but forgot to put in my question above.

**Comment by hickeyma** [comment]
Well, if you don't clean up the release from v2, it will remain visible to v2.  The goal of the tool is to migrate and cleanup releases.

Helm will show what releases are available. If you don't cleanup, then they are still available.

I am unsure what you are looking for the tool to do.

**Comment by srinivasev** [comment]
Hi @hickeyma ,

Thanks for the clarification.
