### ISSUE TITLE
Asset for Darwin_arm64 missed in v0.10.0

### ISSUE THREAD

**Issue by westwind-sc** [helm/helm-2to3#205]
Asset for Darwin_arm64 existed in [v0.8.2](https://github.com/helm/helm-2to3/releases/tag/v0.8.2) and [v0.9.0](https://github.com/helm/helm-2to3/releases/tag/v0.9.0), but missed in [v0.10.0](https://github.com/helm/helm-2to3/releases/tag/v0.10.0)

As `helm plugin install https://github.com/helm/helm-2to3` is using the latest version, the missing will cause install failure.
Could you help to publish the asset for Darwin_arm64 missed in v0.10.0?

Note: This is not a blocking issue, as developer could build the plugin locally.

**Comment by rimusz** [comment]
fixed in https://github.com/helm/helm-2to3/releases/tag/v0.10.1
