### ISSUE TITLE
failed to create: Secret "sh.helm.release.v1.v54" is invalid: data: Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by udayalwala** [helm/helm-2to3#206]
I am trying to convert chart from helm 2to3. release has almost 63 revisions. all this information stored as configmap in helm2. but while converting the release from helm 2to3 i am getting the error as below

Error: create: failed to create: Secret "sh.helm.release.v1..v54" is invalid: data: Too long: must have at most 1048576 bytes
Error: plugin "2to3" exited with error
helm.go:76: [debug] plugin "2to3" exited with error

could any suggest this. I need complete revisions information in helm3 also.

**Comment by hickeyma** [comment]
@udayalwala This looks like the issue Helm encounters when it tries to store a record which exceeds the 1M limit set by etcd. Not sure how Helm 2 allowed it to be stored in the first place, as I thought ConfigMaps have a similar limit. Check out this [Helm issue](https://github.com/helm/helm/issues/9788) and [this issue](https://github.com/helm/helm/issues/6711) for more details. 

I am unsure the best way to get around this issue. You could try using the `--release-versions-max` flag when migrating and set the limit to the last 5 deployed releases and see if that works. It may however also have the same problem. It is probably going to be trial and error to see if any of the latest release versions work.

In parallel, you could try installing the chart as a separate release to see if the chart installs correctly or if it has the same problem. You would then know that the chart probably contains some unnecessary files which are bloating the release.

**Comment by hickeyma** [comment]
Closing as no response from OP.
