### ISSUE TITLE
Default behaviour of convert looks to be cleaning v2 releases when it should leave them

### ISSUE THREAD

**Issue by GavBurke** [helm/helm-2to3#211]
I've recently taken over a project where the helm 2to3 convert has been used for some time, so we seem to be in a place where we have no v2 releases so I've been asked to cleanup the v2 releases now.  Looking at previous code, the convert was done with the following command
`helm 2to3 convert $NS --tiller-ns $TILLER_NS`

According to [https://github.com/helm/helm-2to3#migrate-helm-v2-releases](https://github.com/helm/helm-2to3#migrate-helm-v2-releases), and even the output of `Note: The v2 release information still remains and should be removed to avoid conflicts with the migrated v3 release.`, the default behaviour seems to be for the v2 release versions to be retained, which the above command should be doing, however, when I have come to cleanup the releases, the converted releases do not appear in the list that are being cleaned.  The clean command I'm running being
`helm 2to3 cleanup --release-cleanup --tiller-ns $TILLER_NS --skip-confirmation`

Running the above cleans only the releases which were skipped with there being more than 10 releases and the default of 10 conversions applied, but I expected the cleanup to also need to remove all 10 that were converted, given the convert command _did not_ have the `--delete-v2-release` flag set??

**Comment by hickeyma** [comment]
@GavBurke To help troubleshoot this issue, I have unfortunately more questions than answers.

Are the 10 converted release versions still in the cluster or were they already removed? You can check using a command similar to the following: `kubectl get configmap -n <tiller_namespace> -l "OWNER=TILLER" | awk '{print $1}' | grep -v NAME | cut -d '.' -f1`

How do you know the previous convert removed them? They could have been deleted from the cluster directly.

**Comment by hickeyma** [comment]
Also, `cleanup` command needs to have the specific release name (`--name <release_name>`) or otherwise it will cleanup all v2 releases.

**Comment by GavBurke** [comment]
@hickeyma We use `kubectl -n $TILLER_NS get configmap --ignore-not-found | grep -Eq "^$NS\.v[0-9]+ "` to find any existing v2 releases, and if found then run the `helm 2to3 convert $NS --tiller-ns $TILLER_NS`, which by default converts the newest ten.

So maybe I'm misunderstading what a `kubectl get configmap` should show afterwards, but after we've got an output like so

```
2022/07/01 14:08:06 Release "borg" will be converted from Helm v2 to Helm v3. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:06 [Helm 3] Release "borg" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v1" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v1" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v2" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v2" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v3" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v3" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v4" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v4" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v5" will be created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] ReleaseVersion "borg.v5" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 [Helm 3] Release "borg" created. 
July 1st 2022 15:08:10Error
2022/07/01 14:08:07 Release "borg" was converted successfully from Helm v2 to Helm v3.
```

When I run that get configmap command you provided, I get `borg` printed out five times... I expected five v2 and five v3 releases if the default behaviour is to leave?

As now when I go an run `helm 2to3 cleanup --release-cleanup --tiller-ns $TILLER_NS --skip-confirmation`, it says there's nothing to clean, but there _should_ be the older give converted releases to clean?

> Also, `cleanup` command needs to have the specific release name (`--name <release_name>`) or otherwise it will cleanup all v2 releases.

Yep, this is what we want.  We have an individual tiller namespace for each of our deploys.

**Comment by hickeyma** [comment]
> As now when I go an run helm 2to3 cleanup --release-cleanup --tiller-ns $TILLER_NS --skip-confirmation, it says there's nothing to clean, but there should be the older five converted releases to clean?

Yes, if they still exist in the cluster. That was the `kubectl` command I gave above which should return any v2 release left in the cluster.

**Comment by GavBurke** [comment]
Okay, then this is my misunderstanding, not realising the place to "look" for v2 releases differs from v3.... I've just ran `helm 2to3 cleanup --release-cleanup --tiller-ns $TILLER_NS --dry-run` on the above environment and indeed do see the five previous releases to be deleted.  Presumably then someone had cleared up the other ten releases previously for me to have seen that behaviour.  Thanks @hickeyma (y)
