### ISSUE TITLE
Convert configmaps to original helm value yaml?

### ISSUE THREAD

**Issue by cveld** [helm/helm-2to3#223]
I am migrating an existing kubernetes cluster but the original helm2 invocations are lost. I only have the configmaps lying around in the cluster. Are the original input parameters stored in such a configmap? If so, is it possible to extract this with this tool?

When I run:

`helm 2to3 convert redis.v2 --dry-run -t redis --tiller-out-cluster --release-storage configmaps`

I get the error:

`Error: redis.v2 has no deployed releases`

**Comment by cveld** [comment]
Alright, I had to remove the version suffix. Running the command with release name `redis` did yield results.

**Comment by gogowaiting** [comment]
I had the same problem，my iam app config in default namespace kube-system, helm2 list had iam relsease info but excute:
2to3 convert --dry-run  -s configmaps iam

`Error: iam has no deployed releases`

**Comment by hickeyma** [comment]
Closing as resolved.
