### ISSUE TITLE
Approve PR's and create release

### ISSUE THREAD

**Issue by MartijnPDirekt** [helm/helm-2to3#228]
I would like to use the latest version of this package without forking. Could you please have a look at the open PR's created by dependabot and after that create a release. 
Thanks in advance.

**Comment by MartijnPDirekt** [comment]
@hickeyma, seems like you are the most active person in this repo. Could you approve the PR's and create a new release.

**Comment by hickeyma** [comment]
@MartijnPDirekt Updated and new release cut.
