### ISSUE TITLE
v0.11.0 missing release assets

### ISSUE THREAD

**Issue by micahbeeman-wf** [helm/helm-2to3#242]
Looks like https://github.com/helm/helm-2to3/releases/tag/v0.11.0 is missing the usual `*.tar.gz` release assets that previous tags contained. @hickeyma I noticed you reverted the docker build changes in https://github.com/helm/helm-2to3/pull/241 but the latest tag still looks to be failing in circleci so the assets weren't created.

Can someone take a look?

**Comment by hickeyma** [comment]
@micahbeeman-wf It was WIP. Fixed now.
