### ISSUE TITLE
How plugin should react when errors occur during an operation

### ISSUE THREAD

**Issue by hickeyma** [helm/helm-2to3#38]
This issue is to decide on how the plugin should behave when an error occurs during an operation.

This is the proposal:
- Move configuration:
   - Display error if it occurs but continue on creating directories, files etc. for the different configurations
- Convert releases:
   - Exit when an error occurs, displaying the error
- Cleanup:
   - Exit when an error occurs, displaying the error

**Comment by rimusz** [comment]
Sounds good
