### ISSUE TITLE
Error: release: already exists

### ISSUE THREAD

**Issue by rustycl0ck** [helm/helm-2to3#45]
Installed a release with helm2 along with `tiller` plugin. This creates the release in secrets `my-releasee-name.v1` format already. Thus, the plugin fails to migrate anything from v2 to v3.

```
$ helm3 2to3 convert --tiller-out-cluster --tiller-ns my-ns consul
Release "consul" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "consul" will be created.
[Helm 3] ReleaseVersion "consul.v1" will be created.
Error: release: already exists
Error: plugin "2to3" exited with error
```

**Comment by hickeyma** [comment]
@rustycl0ck Is this a duplicate of #30 ?

**Comment by rustycl0ck** [comment]
Yes, It is dumplicate. I will close this and follow up on the status of #30.

**Comment by hickeyma** [comment]
ok, thanks @rustycl0ck

**Comment by zc-hemenfei** [comment]
Excuse me , How do you solve this situation? @hickeyma

**Comment by rustycl0ck** [comment]
@zc-hemenfei This was fixed in [Helm v3-beta4](https://github.com/helm/helm/releases/tag/v3.0.0-beta.4). Thus, if you are using helm-v3.0.0 or later, you won't encounter this.
