### ISSUE TITLE
Don't throw error for already converted release

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm-2to3#46]
It is possible to not throw error if u already convert release?
for ci/cd it would be useful avoid use try/catch or equivalent.  
maybe with additional flag `--ignore-converted`

**Comment by rimusz** [comment]
@alexandrsemak until we implement it you can run it with `|| true`

**Comment by karuppiah7890** [comment]
I can take a shot at this! This is the first time I'm going to try to contribute to this repo, so I'll ping if I have any questions. Also, please do put any pointers that I have to keep in mind while working on this! 😄

**Comment by hickeyma** [comment]
@karuppiah7890 Can you hold back on this. Not sure we want to do this yet. Let me get back to you on it.

**Comment by karuppiah7890** [comment]
Sure! I was just trying out the plugin for now. And I had some questions on how to go about this issue. Let me know if it's needed. I'll resume then 😄

**Comment by hickeyma** [comment]
@alexandrsemak Currently, the plugin works as follows:
- Retrieves the Helm v2 release version/revisions from storage in clusters
- Maps the release versions to Helm v3 metadata
- Calls Helm v3 storage API to store each release version. The storage API throws an error if there is an issue which includes if the release version already exists in the cluster

To check if a release is already converted would require retrieving the release versions through Helm v3 API. Then potentially iterating through all the versions to see if a version or all versions exist to be certain.
This is necessary as it cannot be known if the Helm release version object in the cluster is converted or not. It may have been added previous to migration.

@alexandrsemak @karuppiah7890 @rimusz I am not sure we want to add extra layers of checking for a use case that can be handled easily enough by the caller of the command. I would think the plugin which is essentially a tool, should remain as simple as possible. What do you think?

**Comment by rimusz** [comment]
I'm in favour of the simple plugin as well, no needs to make it too complicated.

Running convert with  `|| true` easily moves the problem.

**Comment by alexandrsemak** [comment]
kk, it is just proposal i am ok with leave as is

**Comment by hickeyma** [comment]
Closing following discussion agreement.
