### ISSUE TITLE
Unwanted behaviour when cleanup performed not using plugin

### ISSUE THREAD

**Issue by hawksight** [helm/helm-2to3#49]
Ok so I converted a cert-manager release from vv2 to v3:

```
❯ helm 2to3 convert --tiller-ns tiller cert-manager

Release "cert-manager" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "cert-manager" will be created.
[Helm 3] ReleaseVersion "cert-manager.v1" will be created.
[Helm 3] ReleaseVersion "cert-manager.v1" created.
[Helm 3] Release "cert-manager" created.
Release "cert-manager" was converted successfully from Helm 2 to Helm 3. Note: the v2 releases still remain and should be removed to avoid conflicts with the migrated v3 releases.
```

Release existed in v2 & v3 as expected:

```
# helm2
❯ helm ls

NAME            REVISION    UPDATED                     STATUS      CHART                    APP VERSION    NAMESPACE
anchore         7           Tue Apr 16 13:12:03 2019    DEPLOYED    anchore-engine-0.12.1    0.3.3          default
cert-manager    1           Mon Apr 15 17:16:11 2019    DEPLOYED    cert-manager-v0.7.0      v0.7.0         cert-manager

#helm3
❯ helm3 ls -n cert-manager

NAME            NAMESPACE       REVISION    UPDATED                                    STATUS      CHART
cert-manager    cert-manager    1           2019-04-15 16:16:11.590230902 +0000 UTC    deployed    cert-manager-v0.7.0
```

So I attempted to delete the v2 release hoping that it would go from v2, remain in v3 and the pod would survive:

```
❯ helm delete cert-manager

Error: deletion completed with 1 error(s): release "cert-manager": object "" not found, skipping delete

❯ helm ls                                                                                                                  
NAME       REVISION    UPDATED                     STATUS      CHART                    APP VERSION    NAMESPACE
anchore    7           Tue Apr 16 13:12:03 2019    DEPLOYED    anchore-engine-0.12.1    0.3.3          default

❯ helm3 ls -n cert-manager

NAME            NAMESPACE       REVISION    UPDATED                                    STATUS      CHART
cert-manager    cert-manager    1           2019-04-15 16:16:11.590230902 +0000 UTC    deployed    cert-manager-v0.7.0
```

But unfortunately the actual pods were gone:

```
❯ kgp -n cert-manager

No resources found.
```

So I had the v3 release but no pods living under it (in any namespace).

## Sort of fix..

As I wasn't so bothered and didn't have much custom config, I decided to upgrade the v3 release. I had to upgrade the chart from v0.7.0 to v0.10.0 as before I did that I got this:

```
❯ helm3 upgrade cert-manager ./jetstack-cert-manager -n cert-manager
Error: validation: chart.metadata is required
```

On that basis I assumed that the older version of the chart did not meet the new requirements for helmv3.

For anyone who has similar this is my upgrade path:
```
helm3 search hub cert-manager
helm3 pull jetstack/cert-manager
helm3 upgrade cert-manager jetstack/cert-manager -n cert-manager --dry-run --debug

# actul upgrade
❯ helm3 upgrade cert-manager jetstack/cert-manager -n cert-manager

Release "cert-manager" has been upgraded. Happy Helming!
NAME: cert-manager
LAST DEPLOYED: 2019-09-27 15:49:02.86515 +0100 BST
NAMESPACE: cert-manager
STATUS: deployed
NOTES:
cert-manager has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://docs.cert-manager.io/en/latest/reference/issuers.html

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://docs.cert-manager.io/en/latest/reference/ingress-shim.html

# check release
helm3 ls -n cert-manager

NAME        	NAMESPACE   	REVISION	UPDATED                            	STATUS  	CHART
cert-manager	cert-manager	2       	2019-09-27 15:49:02.86515 +0100 BST	deployed	cert-manager-v0.10.0
```

## Question

Once I've used `helm 2to3 convert ...` and have a release in both v2 & v3 - should I be able to delete the v2 release? Should the pods transfer ownership to the v3 release?

Or does that only happen when I use the `--delete-v2-releases` flag?

Finally note my delete command errored but still seemed to delete the release which was confusing. Any advice appreciated.

**Comment by rimusz** [comment]
it happens with the `--delete-v2-releases` flag if you skipped it can clean later one with https://github.com/helm/helm-2to3#clean-up-helm-v2-data

**Comment by rimusz** [comment]
and btw cert-manager from v0.7 to v0.10 is a better a clean install

**Comment by hawksight** [comment]
Thanks @rimusz - but in this case I had another release in v2 so I didn't want to use the cleanup just yet.

Are you saying that essentially once converted, in theory deleting either v2 or v3 release would delete the pods / resource created by the release?

I should convert all releases and then use the `cleanup` command to remove all v2 stuff basically? I shouldn't try and remove manually 1 by 1?

Also your probably right! Been a while since I installed it but nice that it seemed to work with an older version.

**Comment by hickeyma** [comment]
@hawksight That is correct. The tool on cleanup, just removes Helm v2 objects and not the underlying Kubernetes resources. 

The user SHOULD not need to go around deleting things. If they do, then there is an issue in the plugin.

**Comment by rimusz** [comment]
@hawksight 
yes to both questions :)

**Comment by hickeyma** [comment]
Ok, so maybe this is a docs issue to add a note to not delete anything and let `cleanup` do it.

**Comment by hickeyma** [comment]
@hawksight Thanks for  the feedback so far. So we can improve the UX. Where in the README/docs made you want to delete the v2 data directly?

**Comment by hawksight** [comment]
Thanks both for answers.
These are my thoughts so far, and I'll preface this with, really nice idea to have the plugin do all the hard work.

### relating to this issue
For my first release migration I wanted to be sure it went across to v3 before using any `--delete-v2-release` flag.. incase it went wrong.

```
Release "cert-manager" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "cert-manager" will be created.
[Helm 3] ReleaseVersion "cert-manager.v1" will be created.
[Helm 3] ReleaseVersion "cert-manager.v1" created.
[Helm 3] Release "cert-manager" created.
Release "cert-manager" was converted successfully from Helm 2 to Helm 3. Note: the v2 releases still remain and should be removed to avoid conflicts with the migrated v3 releases.
```

^ See the bit about the note ... `the v2 releases still remain and should be removed`

I then went back and tried the same command with that flag... but it errored at that point:
```
❯ helm 2to3 convert --tiller-ns tiller --delete-v2-releases cert-manager

Release "cert-manager" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "cert-manager" will be created.
[Helm 3] ReleaseVersion "cert-manager.v1" will be created.
Error: release: already exists
Error: plugin "2to3" exited with error
```

I though not big deal.. I can just delete it.. hence this issue :)
1) Maybe make the Note more explicit - yes v2 release needs to be removed but only via the right method.
2) Maybe the convert command can detect when its already converted, log that to the user and then just remove the release in v2. Means you could run the command once, see it's converted just fine and then run again with the `--delete-v2-releases` flag.
3) Or maybe it might just be easier to add at `helm 2to3 remove-v2-release <release>` which only remove the one release?
4) Or instead of `--delete-v2-releases`  being an optional flag, make it the default, to stop people then manually deleting like  did. Maybe make the flag the opposite and force people to choose to have the release still exist in v2 `--keep-v2-releases`.

### relating to the cleanup command

I think `helm 2to3 cleanup` command makes sense after re-reading it. But I have about 5 clusters, and wanted to try this out on a devlike cluster. So if I run cleanup, then I'll kill all the config for v2 on the other clusters. (${HOME}/.helm)

 Out of scope of this issue, but could the `helm 2to3 cleanup` have a flag to not remove the `${HOME}/.helm`. 
Eg. so I could cleanup my first cluster.. then move on to another one.
^ Might be common for people to want to do that.
^ Also sounds horribly like giving the people the option not to delete the release and then getting into issues later, so I get that I'm being contradictory in my two points here

### on the backup step
Also:
> Backup v2 data

Maybe add a command for people to run.. otherwise they might just skip.  Something like `tar -czvf ~/Downloads/dot-helm.targz ~/.helm` might help. But maybe improve on my terrible command.

**Comment by hickeyma** [comment]
@hawksight Thanks for the great feedback. I had pushed a PR before your comments. I will look to integrate your comments into the PR.

**Comment by hickeyma** [comment]
Re-triaging this as an UX bug. Needs better clarification for the user when migrating and cleanup.

**Comment by hickeyma** [comment]
@hawksight To help improve the UX, we have done the following:
- Improved readability in the README around cleanup: https://github.com/helm/helm-2to3/pull/50
- Updated the removal message after convert to emphaise use `helm cleanup`: https://github.com/helm/helm-2to3/pull/51
- Extended cleanup functionality to allow cleanup to be done in individual parts as well (config, release data and tiller): https://github.com/helm/helm-2to3/pull/53

Let me know if you think these changes provide better UX.

**Comment by rimusz** [comment]
@hawksight just keep in mind that #51 and #53 have been only merged to master and will be released in `2to3` v0.1.4 maybe this week

**Comment by hickeyma** [comment]
Ping @hawksight. Are you happy with the updates here to improve the UX?

**Comment by hawksight** [comment]
hey both, I'll check the next release out as soon as I see it (maye be away for a couple weeks).
I read through the PRs #50, #51 and #53, and they all look to make things clearer.
So I still have more migrations and will continue them with the newer instructions.
Thanks for taking the feedback onboard and updating so quickly.

**Comment by hickeyma** [comment]
Ok, thanks @hawksight for your feedback. Let us know how you get on when testing again.
