### ISSUE TITLE
plugin fails to install

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-2to3#75]
Spending today testing the Helm 2 to Helm 3 migration path using the 2to3 plugin!

When attempting to install 2to3 on a fresh install, I see this on Ubuntu:

```
><> helm plugin install https://github.com/helm/helm-2to3
Downloading and installing helm-2to3 v0.1.6 ...
https://github.com/helm/helm-2to3/releases/download/v0.1.6/helm-2to3_0.1.6_linux_amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: plugin install hook for "2to3" exited with error
```

It looks like the install script refers to a release that hasn't been released yet.

**Comment by rimusz** [comment]
plugin v0.1.6 was released

**Comment by hickeyma** [comment]
@bacongobbler I think this was a case of timing here! :)  Release v0.1.6 got held up and went out of sync. Can you try it again?

**Comment by bacongobbler** [comment]
works now. Thanks!
