### ISSUE TITLE
Add raw values to v3 metadata

### ISSUE THREAD

**Issue by hickeyma** [helm/helm-2to3#83]
Add fix for Helm issue https://github.com/helm/helm/issues/6354.  Fixes issue with `helm show values`.

***Note: This issue is blocked until https://github.com/helm/helm/pull/6841 lands which should be available in Helm 3 RC-2. ***

**Comment by hickeyma** [comment]
I will work on this once RC-2 is released.

**Comment by bacongobbler** [comment]
This can be closed as https://github.com/helm/helm/pull/6841 won't actually add anything to the release metadata. It's just changes how charts are loaded into memory so we can access the raw files. :)

**Comment by hickeyma** [comment]
Sure, thanks @bacongobbler. After the review today I realised that.

**Comment by hickeyma** [comment]
Closing as no data being persisted from  helm/helm#6354.
