### ISSUE TITLE
bump to rc.3 once released

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-2to3#86]
https://github.com/helm/helm/pull/6866 introduced a breaking change to the storage backend which will affect how 2to3 creates releases. A larger explanation/justification for the breaking change was provided in https://github.com/helm/helm/pull/6881#issuecomment-550364678. The 2to3 plugin should cut a new release compiled against Helm 3.0.0-rc.3 once it's been released later today to be compatible with Helm 3.0.0.

**Comment by rimusz** [comment]
sure

**Comment by hickeyma** [comment]
@bacongobbler This is not a breaking change for the plugin. No changes are required.

FYI, we would always update to the latest release of Helm 3 in any case.

**Comment by hickeyma** [comment]
I will update once RC-3 is released.

**Comment by bacongobbler** [comment]
The call to `cfg.Releases.Create` on [line 97](https://github.com/helm/helm-2to3/blob/6a55fabae68bf7bc9a4eb7878869e39a492c1437/pkg/v3/release.go#L97) may migrate a Helm 2 release as the older Helm 3 metadata. That might not be compatible with Helm 3.0. I'll have to check and confirm just to be 100% sure, but in any case I wanted to reach out. In either case, updating to rc.3 will remove any doubts :)

**Comment by bacongobbler** [comment]
It was identified from https://github.com/helm/helm/pull/6881#issuecomment-550382661 that this may not actually be a backwards-incompatible change. Phew!

**Comment by hickeyma** [comment]
In middle of something at moment but will try and get to it shortly. Off hand, should be ok. Will check shortly. Thanks for reaching out @bacongobbler

**Comment by hickeyma** [comment]
@bacongobbler Looking at it, it works as expected. This is because the plugin interfaces with the Helm object field name definitions and not the persisted object field names. It would only be affected if the Helm object definitions changed and/or relevant API changed.
