### ISSUE TITLE
How to answer yes for all question?

### ISSUE THREAD

**Issue by zodiac182** [helm/helm-2to3#93]
If I want to run it with ansible, how to answer yes for all questions when doing migration to helm v3?

\#  helm3 2to3 move config
2019/11/14 08:53:51 WARNING: Helm v3 configuration maybe overwritten during this operation.
2019/11/14 08:53:51 
[Move Config/confirm] Are you sure you want to move the v2 configration? [y/N]:

**Comment by rimusz** [comment]
this should do it:
```
yes | helm3 2to3 move config --dry-run
```

**Comment by zodiac182** [comment]
> this should do it:
> 
> ```
> yes | helm3 2to3 move config
> ```

It works, thank you very much.
