### ISSUE TITLE
Migrating release dose not always work

### ISSUE THREAD

**Issue by halradaideh** [helm/helm-2to3#94]
I have tried to migrate all the release from Helm v2 to Helm v3 using the plugin, only two out of 25 get migrated, when i tried to migrate them again the plugin fails with error stating that the release already exist, using helm3 ls -a dose not show it !

i can't provide any information about helm 2, because i made clean up, but helm3 still exist.

**Comment by elfhack** [comment]
@halradaideh you need helm ls --all-namespaces now

**Comment by halradaideh** [comment]
@elfhack isn't there a proper documentation for deferences between helm 2 and 3 ?

**Comment by karuppiah7890** [comment]
You can check the `helm ls --help` command. `-a` never meant all namespaces if that was the expectation

For v2:

```
-a, --all                   Show all releases, not just the ones marked DEPLOYED
```

For v3:

```
-a, --all              show all releases, not just the ones marked deployed or failed
      --all-namespaces   list releases across all namespaces
```

**Comment by karuppiah7890** [comment]
`--all-namespaces` is a new feature in helm3, which wasn't present in helm2

**Comment by halradaideh** [comment]
thank you

**Comment by hickeyma** [comment]
@halradaideh Worth looking at [v3 docs](https://helm.sh/docs/) and [changes section](https://helm.sh/docs/faq/#changes-since-helm-2)
