### ISSUE TITLE
Got Error: RELEASE_NAME has no deployed releases

### ISSUE THREAD

**Issue by smeeklai** [helm/helm-2to3#97]
I'm currently using Helm with Tillerless option. When I tried to convert a release, I got `Error: RELEASE_NAME has no deployed releases` error, regardless whether I used `--dry-run` or not

```
$ helm3 2to3 convert --dry-run grafana --tiller-out-cluster
2019/11/26 16:58:34 NOTE: This is in dry-run mode, the following actions will not be executed.
2019/11/26 16:58:34 Run without --dry-run to take the actions described below:
2019/11/26 16:58:34
2019/11/26 16:58:34 Release "grafana" will be converted from Helm v2 to Helm v3.
2019/11/26 16:58:34 [Helm 3] Release "grafana" will be created.
Error: grafana has no deployed releases

Error: plugin "2to3" exited with error
```

Versions:
Helm: `2.16.1`
Helm-tillerless plugin: `0.9.3` (just upgraded from `0.8.1` after I got the error)

**Comment by rimusz** [comment]
what `helm tiller run -- helm list` shows you?

**Comment by smeeklai** [comment]
I store releases in their respective namespace. E.g., the above release is stored in a namespace called `monitoring`.

So `helm tiller run monitoring -- helm list` gave me the correct result:

| NAME | REVISION | UPDATED | STATUS | CHART | APP VERSION | NAMESPACE |
| ------ | ---------- | ---------- | -------- | ------- | -------------- | ------------- |
| grafana | 23 | Tue Sep 24 18:06:01 2019 | DEPLOYED | grafana-3.8.15 | 6.3.5 | monitoring |
| ... | ... | ... | ... | ... | ... | ... |

**Comment by smeeklai** [comment]
Btw, I ran `export HELM_HOST=localhost:44134 && helm tiller start-ci NAMESPACE` when I need to use Helm so I ran the command and then used the plugin

**Comment by rimusz** [comment]
the you need to use one more flag `--tiller-ns` and provide the namespace name for each release

**Comment by smeeklai** [comment]
Thank you. It certainly fixed the issue. Sorry for not reading the help message properly

**Comment by rimusz** [comment]
no worries, glad it is working for you

**Comment by hickert33** [comment]
I am seeing the same error, tiller is in the kube-system namespace using secrets to hold v2 configuration.  

$ helm3 2to3 convert microservice --dry-run
2020/01/23 12:06:07 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/01/23 12:06:07 Run without --dry-run to take the actions described below:
2020/01/23 12:06:07
2020/01/23 12:06:07 Release "microservice" will be converted from Helm v2 to Helm v3.
2020/01/23 12:06:19 [Helm 3] Release "microservice" will be created.
Error: microservice has no deployed releases
Error: plugin "2to3" exited with error

Any ideas?

**Comment by hickeyma** [comment]
@hickert33 This has same symptoms but is a different issue. Do you mind raising a new issue to better track this?

**Comment by rimusz** [comment]
@hickert33 you are missing flag `--release-storage secrets`

**Comment by hickeyma** [comment]
@rimusz The `--release-storage` flag is only used when the plugin is connecting to an out of cluster Tiller. Otherwise, it picks up the storage backend from Tiller in the cluster.

I think it is worth opening the new issue to at least track @hickert33 issue.

**Comment by rimusz** [comment]
then yes we need a new issue

**Comment by hickert33** [comment]
Thanks! I created #112

**Comment by suciuandrei94** [comment]
Hello guys, I've altered an existing GO library to migrate secrets to configmap so this problem with migration doesn't happen anymore.

[here](https://github.com/suciuandrei94/tiller-releases-converter)

**Comment by hickeyma** [comment]
> Hello guys, I've altered an existing GO library to migrate secrets to configmap so this problem with migration doesn't happen anymore.

@suciuandrei94 This is not related to issue, thanks.
